BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBXXX XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB

    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXX
      XXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXFFFFFFFFFFFFFFFF XX X XXXXXXXX
      XXXXXX
      BB BBBBBBB
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
        XXXXXX
        XXXXXXXX XXXXXXXXX
      XXXX
      BBBBB
    XXXXXX

    BB BBB
    XXXX XXXXXXXXXXXXXXXXXX
      BBB BB BB BBB
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX

        XXXX XXXXX X XXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX
          BB BBBBBBBB
          XXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX
          BBBB
          XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          BBBBB

          XXXX XXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXX
              XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
                  BB BBBBBBBBB BB BBBBBBBBXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  BBBB BBBBBBBBB BB BBBBBBBBBXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                  BBBB BBBBBBBBB BB BBBBBBBBBBXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                  BBBB BBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                  BBBBXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBBXX
                  BB BBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBX XXXXXXXXBBBBBBBBB
                XXXXXXX
                BB BBBBBBBBBB
                XXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                BBBBB
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXXXX FFFFFFF F FF X FFFFFFF F FFXXXXXXX
              XXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX
          BB BBB BBBBBBBBBB BBB BBBBBBBBBBBBBBB
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBX
            XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXX
            X XXXXX
          XXXX
          BBBBB
          BB BBB BBBBBBBBBBBBBBB
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBX
            XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXX
            X XXXXXXXXX
          XXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXX
              X XXXXXXXXX
            XXXXXXXXX
          XXXXXXX
          BBBBB
        XXXXXX

      XXXXXX
      BBBBBB
    XXXXXX

    BBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXX XXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXX
      BB BBBBBBB
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX
        X XXXXX XXX XXXXXXXXX
      XXXX
      BBBBB
    XXXXXX
    BBBBB

BBBBBBBB