BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBXXXXXXXX XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXX

      XXXX XXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXXXXX
          X XXXXXX XXX XXXXXXXXXX
        XXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXX XXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXX
              XXXXXXFFFFFFF F FF X FFFFFFF F FFXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFF XXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXX XX XXXXXXX XXXXXXXXXXXX
          XXXXXX
        XXXXXX

        XXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX
            XXXXX FFFFFFFFFFFFFFFF XXX X
          XXXXXXXXX
        XXXXXXX

        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXX XXXXXXXX XXXX XX XXXXXXXXXX XX XXXXXXXX XXXXXXXXXXXX
          XXXXX XXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
        XXXX

      XXXXXX
    XXXXXX
BBBBBBBB