BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBB
XXXX XXXXXXXXXX XXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Paramètres de prix') XXXXX

    BB BBBBBBBB
      BBB BBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          
        XXXXXX
      BBBBBB
    BBBBB

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           gettext(u'Prix boost événement (TND/jour)') 
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXX
               XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           gettext(u'Prix publicité (TND/jour)') 
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXX
               XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXXXX
         gettext(u'Enregistrer') 
      XXXXXXXXX
    XXXXXXX
  XXXXXX
XXXXXX
BBBBBBBB BBBB