# Generated by Django 5.2.9 on 2026-03-28 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guard', '0063_alter_ad_options_ad_db_clicks_count_ad_payment_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('registration_link', models.URLField(blank=True, null=True, verbose_name='Registration Link')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'En attente de paiement'), ('PENDING_APPROVAL', 'En attente de validation'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING_PAYMENT', max_length=20)),
                ('visibility', models.BooleanField(default=False, verbose_name='Visible onto platforms')),
                ('is_boosted', models.BooleanField(default=False, verbose_name='Boosted (Top 3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_events', to='guard.location')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-is_boosted', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='events/')),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.event')),
            ],
        ),
    ]
