BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Ajouter un événement') BBBBBBBB BBBBB

BBBBB BBBB
XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXX
        XXXX XXXX XXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXX XXXXXX XXXXXXX X X X X XXXX X XXXXXXX XXX XXXXXXXXXX X XXXXXXXX XXXXX XXXX XXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXX X X X X XXXX XXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXX XXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u"Publication d'événement") XXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXX
             gettext(u"Pour publier votre événement sur FielMedina, des frais de traitement sont requis. Votre événement sera visible dès validation par l'administrateur.") 
        XXXX

        XXXX XXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXX XXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Montant') XXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX gettext(u'Standard') XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X X XXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Visibilité garantie après validation') XXXX
                XXXX XXXXXXXXXX XXX XXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X X XXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Support prioritaire') 
            XXXX
        XXXXXX

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                     gettext(u'Payer et Continuer') 
                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXX XXX XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                 gettext(u'Annuler') 
            XXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXX X X XXXX XXXXX X X XXX XXXXX X X XXXX XXXXX X X XXXXXXXXXXX X X XXXXXXXXXXXXXXXXXX X X XXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Paiement sécurisé par Konnect Network') 
    XXXXXX
XXXXXX
BBBBBBBB BBBB
