BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Tracking Dashboard') BBBBBBBB BBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX
        XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                 gettext(u'Analytics for:')  FFFFFFFFFFFFFF
            XXXXX
             #
 #
 #
 #
 #

        XXXXXX
        
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Period:') XXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX BB BBBBBB BB BBBBBBBXXXXXXXXBBBBBX gettext(u'Today') XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Yesterday') XXXXXXXXX
                XXXXXXX XXXXXXXXXXXX BB BBBBBB BB BBBBBBXXXXXXXXBBBBBX gettext(u'Last 7 Days') XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX BB BBBBBB BB BBBBBBBXXXXXXXXBBBBBX gettext(u'Last 30 Days') XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Last Month') XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX BB BBBBBB BB BBBBBBBXXXXXXXXBBBBBX gettext(u'All Time') XXXXXXXXX
            XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXX X X XXXXXXXXXX X X XXXX XXXXX X X XXX XXXXX X X XXXXXXXX XXXXX X X XXXXXXXXX X X XXX XXXXXXX XXX X X XXX XXXXX X X XXXXXXX XXXXX X X XXXXXXXXX X X XXX XXXXXX X X XXXX XXXXXX X X XXXXXXXXXXXXXXXX
                    XXXXXX
                     gettext(u'Tracking Information') 
                XXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                 #
 #
 #
 #
 #
 #

                XXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Short ID') XXXX
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXX
                 #
 #
 #
 #

            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX
        XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Total clicks') XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                    X
                XXXXXXX
                BBBBB
            XXXXXX
            BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XX FFFFFFFFFFFXFFFFFFFFFFF
            XXXX
            BBBBB
        XXXXXX
        
        XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Human clicks') XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                    X
                XXXXXXX
                BBBBB
            XXXXXX
            BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XX FFFFFFFFFFFXFFFFFFFFFFF
            XXXX
            BBBBB
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX
        XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u"Metric's Evolution Over Time") XXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Top Countries') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Top Cities') XXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Top Browsers') XXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Top Operating Systems') XXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Top Social Referrers') XXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Back') 
        XXXX
    XXXXXX

XXXXXX
BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXX XXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
    X

    XXX X
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX

        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXX X XXXXXXXXX X XXXXXXXXXX
        
        XXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XX XX
        XXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XX XX
        
        XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX X XX X
                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXX X XXXXXXXXXXXXX XX XXX XXX
                XX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX 
                X
            X
        X
        
        XX XXXXXXXXXXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
            
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
            
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        X

        XXXXX XXXXXXXXXXXXXXXX X X
            XXXXXX X
                XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                XXXXXXXX X XXXXX XXXXX XX
                XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXX
            XX
            XXXXXXXXXXX X XXXXXXXX XXXXX XX
            XXXXXX X XXXXX XXXXXXXXXX X XXXXXX X XXXXXXX XX
            XXXXXXXX X XXXXXX XXXXXXXXXX X XXXXXX X XXXXXXX X
        XX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX X XX X
                    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX
                    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                    
                    XXXXX XXXXXXX X X
                        XXXXXXXXXXXXXXXXXXXX
                        XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXX XX
                        XXXXXXX XX XXXXX X gettext(u'Clicks') XX XXXXX XXXXXX XXX
                        XXXXXX X 
                            XXXXXXXXXXX XXXXXXX 
                            XXXXXXX X XXXXX XXXXX XX
                            XXXXXXXXXXX X XXXXX XXXXX XX
                            XXXXXXXXXX X XXXXX XXXXX X
                        XX
                        XXXXXXX X XXXXXX XXXXXXXXX XXXXXX X XX
                        XXXXX X XXXXX XXXXXXXXXXX XXXXXXXXX X XXXXXXXXXXXXXXX XX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXX XXXXXX XXX XXX XXXX X XX
                        XXXXXXX XXXXXXXXXXXX
                        XXXXX X XXXXX XXXXX X
                    XX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        X

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXX X XXXXXXXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXX

            XX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX XXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            X

            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
            
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXX XX X
                XX XXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXX
                XX XXXXXXXXX XXX XXXXXXX XXXXXX XXXXXXXXX XX XXXXXXXXX XX XXXXXXXXXX
                XX XXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XX XXXXXXXXXX
                XX XXXXXXXXX XXX XXXXX XXXXXX XXXXXXX XX XXXXXXXXXX
                XX XXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XX XXXXXXXXX
                XX XXXXXXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXXXX XX XXXXXXX
                XXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXX
            XXX

            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX

            XXXXX XXXXXXX X X
                XXXXXXXXXXXXXXXXXXXX
                XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXX XXX XX
                XXXXXXX XX XXXXX X gettext(u'Clicks') XX XXXXX XXXXXX XXX
                XXXXXX X 
                    XXXXXXXXXXX XXXXXXX
                    XXXXXXXXXXX X XXXXX XXXXX XX
                    XXXXXXXXXX X XXXXX XXXXX X
                XX
                XXXXXXXXXXXX X XXXX X XXXXXXXXXXXXX XX XXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX X XX
                XXXXXXX XXXXXXXXXXXX
                XXXXX X XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X X
            XX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        X

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXX XXXXXXXXXXXX X XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXX gettext(u'No data available') XXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX

    X XXXXX XXX X
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXX
    X
XXXXXXXXX


BBBBBBBB BBBBBBBBBBB
