# Generated by Django 5.2.9 on 2026-04-22 10:14

import django.db.models.deletion
import partners.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
        ('guard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=partners.models.generate_coupon_code, max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_percentage', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('subscription', 'Abonnement'), ('content', 'Contenu (Events & Ads)'), ('both', 'Les deux')], default='both', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compteur de reçus',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('frozen', 'Gelé')], default='pending', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('account_frozen', models.BooleanField(default=False)),
                ('is_temporarily_disabled', models.BooleanField(default=False)),
                ('disabled_reason', models.TextField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('reactivated_at', models.DateTimeField(blank=True, null=True)),
                ('contract_period', models.CharField(blank=True, choices=[('1_month', '1 Mois'), ('3_months', '3 Mois'), ('6_months', '6 Mois'), ('10_months', '10 Mois'), ('12_months', '12 Mois (1 An)')], max_length=20, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('monthly', 'Paiement Mensuel'), ('total', 'Paiement Total')], max_length=10, null=True)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pending_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('konnect_wallet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('active', 'Paiement actif'), ('not_active', 'Paiement non actif')], default='not_active', max_length=20, verbose_name='Statut paiement')),
                ('is_trial', models.BooleanField(default=False, verbose_name="Période d'essai")),
                ('trial_start', models.DateField(blank=True, null=True, verbose_name='Début du trial')),
                ('trial_end', models.DateField(blank=True, null=True, verbose_name='Fin du trial')),
                ('trial_notified', models.BooleanField(default=False, verbose_name='Email expiration envoyé')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('unpaid_subscription', 'Abonnement impayé'), ('unpaid_ad', 'Publicité impayée'), ('email_change', 'Changement email en attente'), ('new_partner', 'Nouveau partenaire'), ('trial_expired', 'Trial expiré')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='partners/ads/mobile/', validators=[partners.models.validate_mobile_image])),
                ('tablet_image', models.ImageField(blank=True, null=True, upload_to='partners/ads/tablet/', validators=[partners.models.validate_tablet_image])),
                ('destination_link', models.URLField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_per_day', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1_month', '1 Mois'), ('3_months', '3 Mois'), ('6_months', '6 Mois'), ('10_months', '10 Mois'), ('12_months', '12 Mois (1 An)')], max_length=20)),
                ('payment_type', models.CharField(choices=[('monthly', 'Paiement Mensuel'), ('total', 'Paiement Total')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('monthly_amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('konnect_payment_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Contrat Partenaire',
                'verbose_name_plural': 'Contrats Partenaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('title_fr', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_fr', models.TextField(blank=True, default='')),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('boosted', 'Boosté')], default='pending', max_length=20)),
                ('is_boosted', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boost_payment_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('boosted_at', models.DateTimeField(blank=True, null=True)),
                ('boost_paid_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guard.eventcategory')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guard.location')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerEventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='partners/events/', validators=[partners.models.validate_image_or_video])),
                ('media_type', models.CharField(default='image', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='partners.partnerevent')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('payment_type', models.CharField(choices=[('subscription', 'Abonnement'), ('boost', 'Boost Événement'), ('ad', 'Publicité')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('client_code', models.CharField(blank=True, max_length=20)),
                ('payment_ref', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('sent_to_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
                'ordering': ['-created_at'],
            },
        ),
    ]
