# Generated by Django 5.2.9 on 2026-04-12 21:36

import django.db.models.deletion
import partners.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
        ('guard', '0072_remaining_from_0071'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compteur de reçus',
            },
        ),
        migrations.AlterModelOptions(
            name='adminnotification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partnerad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partnerevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partnereventmedia',
            options={},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='password',
        ),
        migrations.RemoveField(
            model_name='partnerad',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='partnerad',
            name='discount_applied',
        ),
        migrations.RemoveField(
            model_name='partnerad',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='partnerad',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='partnerad',
            name='konnect_payment_ref',
        ),
        migrations.RemoveField(
            model_name='partnerad',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='partnerad',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='partner',
            name='is_trial',
            field=models.BooleanField(default=False, verbose_name="Période d'essai"),
        ),
        migrations.AddField(
            model_name='partner',
            name='payment_status',
            field=models.CharField(choices=[('active', 'Paiement actif'), ('not_active', 'Paiement non actif')], default='not_active', max_length=20, verbose_name='Statut paiement'),
        ),
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('frozen', 'Gelé')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='partner',
            name='trial_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fin du trial'),
        ),
        migrations.AddField(
            model_name='partner',
            name='trial_notified',
            field=models.BooleanField(default=False, verbose_name='Email expiration envoyé'),
        ),
        migrations.AddField(
            model_name='partner',
            name='trial_start',
            field=models.DateField(blank=True, null=True, verbose_name='Début du trial'),
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='type',
            field=models.CharField(choices=[('unpaid_subscription', 'Abonnement impayé'), ('unpaid_ad', 'Publicité impayée'), ('email_change', 'Changement email en attente'), ('new_partner', 'Nouveau partenaire'), ('trial_expired', 'Trial expiré')], max_length=30),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partnerad',
            name='destination_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='partnerad',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='partners/ads/mobile/', validators=[partners.models.validate_mobile_image]),
        ),
        migrations.AlterField(
            model_name='partnerad',
            name='price_per_day',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='partnerad',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerad',
            name='tablet_image',
            field=models.ImageField(blank=True, null=True, upload_to='partners/ads/tablet/', validators=[partners.models.validate_tablet_image]),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guard.eventcategory'),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='description_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guard.location'),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='title_fr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='partnereventmedia',
            name='media_type',
            field=models.CharField(default='image', max_length=10),
        ),
        migrations.CreateModel(
            name='ReceiptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('payment_type', models.CharField(choices=[('subscription', 'Abonnement'), ('boost', 'Boost Événement'), ('ad', 'Publicité')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('client_code', models.CharField(blank=True, max_length=20)),
                ('payment_ref', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('sent_to_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
                'ordering': ['-created_at'],
            },
        ),
    ]
