BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB
     BB BBBBBB
           gettext(u'Edit Hiking') 
     BBBB
           gettext(u'Add Hiking') 
     BBBBB
BBBBBBBB BBBBB

BBBBB BBBB
XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX X X XXXXXXXX XXXX XXX X X XXXXXXX XXXXXXX XXXXXXXXXXX X X XXX XXXXX X X XXXXXXXXXX X X XXXXXXXXX X X XXX XXXXX X X XXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Dashboard') 
            XXXX
        XXXXX
        XXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Hiking') XXXX
            XXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBB gettext(u'Edit') BBBB gettext(u'Add') BBBBB
                XXXXXXX
            XXXXXX
        XXXXX
    XXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        BB BBBBBB
             gettext(u'Edit Hiking') 
        BBBB
             gettext(u'Add Hiking') 
        BBBBB
    XXXXX
    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BB BBBBBB
             gettext(u'Update the hiking details below') 
        BBBB
             gettext(u'Fill in the details to create a new hiking trail') 
        BBBBB
    XXXX
XXXXXX

XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    
    BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                XXXXXXXXXXX
            BBBBBB
        XXXXXX
    BBBBB 
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXX X X X X XXXX XXXXXXXXXXX
                    XXXXXX
                     gettext(u'Basic Information') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Enter the hiking name in different languages') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
                                     gettext(u'English') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
                                     gettext(u'French') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                    XXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXX 
                                XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to French') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXX 
                                XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to English') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXX X X XXXXXXXXXX X X XXXXXXXXXXXXX X X XXXXXXXXXXXXXXXX XXXXXXX X X XXXXXXXXXXXXXXX X X XXXX XXXXXXXXXXX
                    XXXXXX
                     gettext(u'Description') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Hiking description and details') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
                                     gettext(u'English') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
                                     gettext(u'French') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                    XXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX 
                                XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to French') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX 
                                XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to English') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX XXXXXX XXXXXXX X X XXXXXXXXX X X XXXXXXXXXX X X XXXX XXXXXX X X XXX XXXXXXXXXXX
                    XXXXXX
                     gettext(u'Location and City') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Select the relevant locations and city') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXX XXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXX X XXXXXXXX XXXXXXXXXXXXXXXX X X XXXXXXXX XXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXX X X XXXX X X X X XXX XXXXXXXXXXX
                    XXXXXX
                     gettext(u'Route Locations (Ordered)') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Add locations in the order they appear on the route.') XXXX
            XXXXXX

            
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    
                    
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                 gettext(u'Location')  
                            XXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBB
                                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                        XXXXXX
                        
                        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                                XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    
                                    XXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                         gettext(u'Remove') 
                                    XXXXXXXX
                                XXXXXX
                            BBBBB
                        XXXXXX
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                 gettext(u'Add Next Location') 
            XXXXXXXXX
        XXXXXX
    XXXXXX


    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Geolocation') XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Set the terminus point coordinates') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Images') XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Upload images for this hiking trail (max 10). Images will be automatically optimized.') XXXX
            XXXXXX
            
            
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                        BB BBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                        XXXXXX
                        BBBBB
                        XXXX XXXXXXXXXXXXXXX
                            
                            XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBB gettext(u'Replace Image') BBBB gettext(u'Upload Image') BBBBB
                            XXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                        XXXXXX
                        BB BBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                
                                XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXX
                            XXXXXXXX
                        XXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                 gettext(u'Add Another Image') 
            XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Cancel') 
        XXXX
        XXXX XXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X XXXXXX X X X XXX XXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX X X XXXXXXXX XXXXXXX XXX X X XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                BB BBBBBB gettext(u'Update Hiking') BBBB gettext(u'Save Hiking') BBBBB
            XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXXX

BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        
        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X

    XX XXXXXX XXXXXXX XXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXX XX XXXXXXXXX X
            XXXXXXXXXXXXXX XXXXXX XX XXXXXX XXXXXXX XXXXXXX
            XXXXXXX
        X
        
        XX XXXXX XXX XXXXX XXXXX XXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXX XXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXX XXX XXXX XXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXX XXXXXXXXXXXXXXX X XXX
        
        XX XXXXXX XXX XXXXXXXX XXXXX XXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXXXX XXXXXXXX XX XXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXXX XXXXX XXXXX
        XXXXXXXXXXXXXXXX X XXXXXXXXX X XX
    XXX

    XX XXXXXX XXXXXXX XXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX X XXX 
        
        XX XXXXXXXXXXXXXXX XXXXXXX 
        
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXX XXXXX
        XXXXX XXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXXX XXXXXXXXX
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXX X
             XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXX XXXXX X XXXXXXXXXXXXXXXXXXX
             XX XXXXXXX X
                 XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX XXXXXXXXX X XXX
             X XXXX X
                 XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX X X X X XXXXXXXXXX X XXX
             X
        X

        XX XXXXX XXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX X XXXX
        
        XX XXX XXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXX X XXXXXXXXXX
        X
        
        XX XXXXXXX XXXXXX XX XXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXX

        XX XXXXXX XX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXXX XXXXX XXXXX
        XXXXXXXXXXXXXXXX X XXXXXXXXX X XX
    XXX

    XX XX XXXXXXXXXXX XXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    
    XX XXX XXXX XX XXXXXXXX XXXXXXXXX XXXXX XXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX X
            XXXXX XXXXXX X XXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
    X

    XX XXXXXXXX XX XXXXX XXXXXXXXX XXX XXXXXX XXX XXXXXXXXX
    XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXX XXXXXXXXX X XXX
        XX XXXXXXXX X
            XXX X
                XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX X
                    XXXXXXXXX X XXXXXXXXXXXXXXX
                X
            X XXXXX XXXXXXX X
                XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX
            X
        X

        XX XXXXXX XXXXXXXX XXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
        XXX
        
        XX XXXXX XXXXXXXXX XXXXXXXX XX XX X XXXX XXXXXXXXX XXX XXX XXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX X
        XX XXXXX XXXXXXX
        XXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXX XX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX X XXXXXXX
            XX XXX XXXXXXX XXXX XX XXXXXX XXXXXXXXX XX XXXXXXXXXXXXXXXXX 
            XXXXX XXXX X XXXXXXXXXXX XX XXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXX X XXXXX
            
            XX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXX X XXXXX
            X
            XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
    X
    
    XX XXXXXXXX XXX XXX XXXXXXXX XXXXX XX XXXXXXX XXXXXXXXXX XXXXX XXX
    XX XX XXXXXX XXXX XX XXX XXXXXX XXXXXXXXX XX XXXXXXX XXX XXXXX XXXXXXX XXX XXXXXXXX XXXXXXX
    XX XX XX XXXXXX XXXXXX XXX XXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXX XX XXXXXX
    
    XX 
       XXXXXXXX XX XXXXX XXXXXX XXXX XXX XXXXXX XXXXXXX XX XXXX XXXXXXXX XXXXXXXX
       XXX XXXXX X XXXXXX XXXX XXXXXX XXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXX XXX XXXXX XXXXXX 
       X XXXX XXX X XXXXXXXXXXXXXXXX XX XXX XXXXXXX XXXXXXXXX XX XXXXXX XXX XXXXX
    XX
    
    XXXXX XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
             XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                 XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                 XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                     XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                     
                     XX XXXXXXXXXXXXXXX X
                         XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                         XX XX XXXXX XXXX X XXXXX XXX X XXX XXX
                         XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
                     X XXXX XX XXXXXXXXXXXXXXXXXX X
                          XX XXXXXXXX
                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                     X XXXX X
                          XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX
                     X
                 X
             X
        XXX
    XXX
    
    XX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXX XXX
    X


XXXXXXXXX
BBBBBBBB BBBBBBBBBBB
