BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB
    BB BBBBBB gettext(u'Modifier la pub') BBBB gettext(u'Ajouter une pub') BBBBB
BBBBBBBB BBBBB

BBBBB BBBB

XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            BB BBBBBB gettext(u'Modifier la campagne') BBBB gettext(u'Créer une nouvelle pub') BBBBB
        XXXXX
        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Remplissez les informations, choisissez les dates et procédez au paiement pour activer votre pub.') 
        XXXX
    XXXXXX

    BB BBBBBB BBB BBBBBBBBBBBBBB
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXX X X XXXX XXXXX X X XXX XXXXX X X XXXX XXXXX X X XXXXXXXXXXX X X XXXXXXXXXXXXXXXXXX X X XXX XXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXXXXXXXXXXX gettext(u'Pub verrouillée') XXXXXXXXX X  gettext(u'Cette pub a été payée et ne peut plus être modifiée.') XXXXXXX
    XXXXXX
    BBBBB

    BB BBBBBBBBBBB
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X XXXXX X X X X XXXX XXXXXXXXX X X XXXX X X X X XXX XXXX XXX X X XXX XXXXX X X XXX XXXXX X X XXXXXXXXXX X X XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
         gettext(u'Veuillez corriger les erreurs ci-dessous.') 
    XXXXXX
    BBBBB

    XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
        BBBBBBBBBB

        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX

        XXXX XXXXXXXXXXXXXXXXXX

            
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                     gettext(u'Informations de la pub') 
                XXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                        XXXXX
                            XXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXX
                        XXXXX
                            XXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            
                        XXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                        
                        XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Pub active') XXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX

            
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                     gettext(u'Visuels') 
                XXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX gettext(u'Taille requise : 320×50 px') XXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
                        BB BBBBBBBBBBBBBBBBBBBXXXX XXXXXX XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX gettext(u'Taille requise : 728×90 px') XXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
                        BB BBBBBBBBBBBBBBBBBBBXXXX XXXXXX XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXX
                XXXXXX
            XXXXXX

            
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                     gettext(u'Période de diffusion') 
                XXXXX

                XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX

                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                             gettext(u'Start Date')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXX
                                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX XXXXXX XXXXXXX X X XXXXXXXXX X X XXXXXXXXXX X X XXXX XXXXXX X X XXX XXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX gettext(u'Minimum : demain') XXXX
                        BB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXX

                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                             gettext(u'End Date')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXX
                                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX XXXXXX XXXXXXX X X XXXXXXXXX X X XXXXXXXXXX X X XXXX XXXXXX X X XXX XXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                        BB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXX

                XXXXXX

                
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXX gettext(u'Tarif') XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX X  gettext(u'jour') XXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXX gettext(u'Durée') XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Total') XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX

            
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Annuler') 
                XXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXX
                    XXXXXX
                    XXXXX XXXXXXXXXXXXXBB BBBBBB gettext(u'Mettre à jour') BBBB gettext(u'Enregistrer') BBBBBXXXXXXX
                XXXXXXXXX
            XXXXXX

        XXXXXX
    XXXXXXX
XXXXXX


XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Informations de facturation') XXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Requis pour générer votre facture') XXXX
                XXXXXX
                XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXX XXX XXXX XXXXX
                    XXXXXX
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXX gettext(u'Campagne') XXXXXXX
                    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXX gettext(u'Durée') XXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXX gettext(u'Total à payer') XXXXXXX
                    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Nom')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Prénom')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Email')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Téléphone')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Adresse de facturation')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XX XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                     gettext(u'Veuillez remplir tous les champs obligatoires.') 
                XXXX
                XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXX XXXXXX X X XXXXXXXXX X X XXXXXXXXXX X X XXXX XXXXX X X XXX XXXXX
                    XXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Confirmer et payer via Konnect') XXXXXXX
                XXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Paiement sécurisé via Konnect Tunisia') XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

BBBBBBBB BBBB


BBBBB BBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XX XXXXX XX XXXXX XXXXXXXXXX XXXXXXXXX XX
XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
    XXXXXXX XXXXX XXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
X
XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXX XXXXXXX XXXXXXXXXXX
X
XXXXXXXXXXXXXX X XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXX X
XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXX XXXXXXXXXXX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXX XXXXXXXXXXX X
XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX X
XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXX XXXX XXXXXXXXXXX
X
XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
X
XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXX X XXXXX XXXXXXX XXXXXXXXXXX X
XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX X XXXXX XXXXXXX XXXXXXXXXXX X
XXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X

    XXXXX XXXXXXXXXX X XXX

    XXXXX XXXXXXXXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX    X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX      X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX   X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX      X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX    X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX      X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX      X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX       X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXX X XXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
    XXXXXXXXXXXXXXXXXXXX XX XX XXX

    XXX XXXXXXXXXXXXX X XXXXX
    XXX XXXXXXXXXXX   X XXXXX
    XXX XXXXXXXXX     X BB BBBBBBBBBBXXXXBBBBBX
    XXX XXXXXXXXXX    X XX
    XXX XXXXXXXXX     X XX

    XXXXX XXXXX X X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXXX XX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX
            XXXXXXX
        X
        XXXXXXXXX  X XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXX X XXXXXXXXX X XXXXXXXXXXX

        XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXXX X X X XXX X XXXXX
        XX XXXXXXXXX    XXXXXXXXXXXXXXXXXXX     X XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXX   X XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXX XXXXXX X X XXXXXXXXX X X XXXXXXXXXX X X XXXX XXXXX X X XXX XXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXX XXX X XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXX   X XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXXXXXXXX X XBB BBBBBBXXXXXX X XXXXBBBBXXXXXXXXXXXBBBBBXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    X

    XX XX XXXXXXXXXX XXXXX X XXXX XX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXX      XXXXX
        XXXXXXXXXXX  XXXXXXXX
        XXXXXXXXX    XXXXXX
        XXXXXXXXXXX  XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX     XXXXXXXXX
        BB BBBBBB BBB BBBBBBBBBBBBBBBB
        XXXXXXXXXXXX XFFFFFFFFFFFFXX
        BBBBB
        XXXXXXXXX XXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXX X XXXXXXXXX
            XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX

            XXXXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXXX

            XX XXXXXXXXXXXX XX XXXXXXXXXXX XX XXXXXXXXXXXXXX X
                XXXXXXXXXXX X XXXXX
                XX XXXXXXXXXXX XXXXXXXXXXXXXXX X XXX
                XXXXXXXXXXXXXX
            X
            XXXXXXXXXXXXXXXXXXX
        X
    XXX

    XX XX XXXXXXXXXX XXXXX X XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX

    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXX      XXXXX
        XXXXXXXXXXX  XXXXXXXX
        XXXXXXXXX    XXXXXX
        XXXXXXXXXXX  XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX     XXXXXXXX
        BB BBBBBB BBB BBBBBBBBBBBBBB
        XXXXXXXXXXXX XFFFFFFFFFFFFXX
        BBBBB
        XXXXXXXXX XXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX X XXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
        X
    XXX

    XX XX XXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBB BBB BBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBB
    XXXXXXXXXXX X
        XXXXXXXXXXXXX X XXX XXXXXXFFFFFFFFFFFFXXX
        XXXXXXXXXXX   X XXX XXXXXXFFFFFFFFFFFFXXX
        XXXXXXXXXXXXXXXXXXX
    XXXXX
    BBBBB

    XX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX X
            XX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XXXXXXX

            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX  X XXXXX
            XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX

            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXX
            XXX X
                XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXX XXXXXXX XXXXX XXX XXXXXXXXXXXXXXXXX
                    XXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
                XXX
                XXXXXXXX X XXXXX XXXXXXXXXXXX
            X XXXXX X
                XXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXX
            X

            XX XXXXXXXXXXXXXX X
                XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXX
            X

            XXXXXXXXX X XXXXXXXXXXXXXXX
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   X XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXXX X X X XXX X XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    X XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXX X XXXXXX
            XXXXXXXXXXXX
        XXX
    X

    XX XX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX          X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX   X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX X XX XXXXXX XXX XXXXXXXXX XXXXXXXXXXXXX XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XX X
        XXXXX XXX     X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXX   X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXX     X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXX XX XXXXXXX XX XXXXXX XX XXXX XX XXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX     X XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXX XXXXXXXXXX

        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXX
        XXX X
            XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXX XXXXXXX
                XXXXXXXX X XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
                XXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXX XXXX XXXXXXX XXX
            XXX
            XXXXXXXXXXXX X XXXXX XXXXXXXXXXXX
        X XXXXX X
            XXXXXXXXXXXXXXXXX XX XXXXXXXXX XX XXXXXXX XX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX     X XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XX XXXXX XXX XXXXXXXXX
            XXXXXXX
        X

        XX XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XX XXXXXXXX XX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX     X XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XX XXXXX XXX XXXXXXXXX
        X
    XXX

    XX XX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX    X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XX XXXXXXXXX
            XXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX XX XXXXXXXXXXXXX XX X
                    XXXXX XXX X XXX XXXXXXXXXXXXXX XXXXXX
                    XX XXXXX XX XXXXXXXX XXXXXXXXXXXX X XXXXX
                    XXXXXXXXXXXXXXXXXXXX
                XXX
            XXX
    X

    XX XXXXXXXXXXXXXX XX XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XX XX XXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXX XX XXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXX XX XX X
        XX XXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXX XXX X XXX XXXXXXXX
        XXXXXXXXXX X XXXXXXXX XX X
            XX XXXXXXXXXXX XXX X XX XXXXXXXXXXX XXX XX X
                XXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXXXXXXXXX
                XXXXXXXXXXX X XXX
            X
        XX
        XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXX
XXX
XXXXXXXXX
BBBBBBBB BBBBBBBBBBB
