BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Ads List') BBBBBBBB BBBBB

BBBBB BBBB
   XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
         XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX XX XXXX XXXXXXXX XXXXX XXXXXX XXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXX XX XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX XXX XX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XX XXX XXXXXX XXXXXXXXXXXX
          gettext(u'List') 
      XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
         XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          gettext(u'Add') 
      XXXX
   XXXXXX

   XXXX XXXXXXXXXXXXXXXX XXXXXX
      XXXXXX XXXXXXXXXXXXXXX
         XXXXXXX
            XXXX
               XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Name') XXXXXXXXXXXX
               XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Link') XXXXXXXXXXXX
               XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Clicks') XXXXXXXXXXXX
               XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Status') XXXXXXXXXXXX
               XXXXXXXXX
            XXXXX
         XXXXXXXX
         XXXXXXX
            BBB BB BB BBB
            XXXX
               XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                     
                  XXXX
               XXXXX

               XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                 
                 XX XXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXX
                 XXXX
               XXXXX

               XXXX
                  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXX
                     
                  XXXXXXX
               XXXXX

               XXXX
                  BB BBBBBBBBBBBB
                  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX
                     XXXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                      gettext(u'Active') 
                  XXXXXXX
                  BBBB
                  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX
                     XXXXX XXXXXXXXXX XXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                      gettext(u'Inactive') 
                  XXXXXXX
                  BBBBB
               XXXXX

               XXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                     BB BBB BBBBBBBBBB
                     XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                         gettext(u'Edit') 
                     XXXX
                     BBBB
                     XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXX
                        XXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                           XXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXX X X XXXX XXXXX X X XXX XXXXX X X XXXX XXXXX X X XXXXXXXXXXX X X XXXXXXXXXXXXXXXXXX X X XXX XXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                         gettext(u'Locked') 
                     XXXXXXX
                     BBBBB

                     XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                         gettext(u'Delete') 
                     XXXXXXXXX
                  XXXXXX
               XXXXX
            XXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBB
            BBBBBB
         XXXXXXXX
      XXXXXXXX
   XXXXXX
BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXX X
    XXXXX XXX X XXXX XXX XXXX
        X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX
X

XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX X
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
    XXX
X
XXXXXXXXX
BBBBBBBB BBBBBBBBBBB