BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Sponsors') BBBBBBBB BBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
         gettext(u'List') 
    XXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Add') 
    XXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX
            XXXX
                XXXX gettext(u'Logo') XXXXX
                XXXX gettext(u'Name') XXXXX
                XXXX gettext(u'Link') XXXXX
                XXXXXXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBBB BB BBBBBBBB
                XXXX
                    XXXX
                        BB BBBBBBBBBB
                            XXXX XXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                        BBBB
                            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'No image') XXXXXXX
                        BBBBB
                    XXXXX
                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX
                        XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXX
                    XXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX  XXXXXXXXXX X XXX XXXXX
                                    XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXX XXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXXX XXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXX XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXX XXXXXXX XXXXXXXXX XXX XX XXXXX XX XXXXXX XXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXXXX XXXXX XXXXX XXX XXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXX
                                XXXXXX
                                 gettext(u'Edit') 
                            XXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXX XXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XX XX XXXXX XX XXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXX XXXXX XX XXX XXXXXX XXXXXXXX XXXXXXXXXX XXXX XXXXX XX XXXXX XXXXXXXX XXXXXXXX XX XXXXX XXXX XXXXX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXX
                                XXXXXX
                                 gettext(u'Delete') 
                            XXXXXXXXX
                        XXXXXX
                    XXXXX
                XXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
            BBBBBB
        XXXXXXXX
    XXXXXXXX
XXXXXX
BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX X
   XXXXX XXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXXX
   XXX
X
XXXXXXXXX
BBBBBBBB BBBBBBBBBBB