BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB
XXXX XXXXX XXX XXXXXXX XXXXXXXXX XXX
BBBBB BBBBB
     BB BBBBBB
           gettext(u'Edit Location') 
     BBBB
           gettext(u'Add Location') 
     BBBBB
BBBBBBBB BBBBB

BBBBB BBBB
XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX X X XXXXXXXX XXXX XXX X X XXXXXXX XXXXXXX XXXXXXXXXXX X X XXX XXXXX X X XXXXXXXXXX X X XXXXXXXXX X X XXX XXXXX X X XXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Dashboard') 
            XXXX
        XXXXX
        XXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Locations') XXXX
            XXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBB gettext(u'Edit') BBBB gettext(u'Add') BBBBB
                XXXXXXX
            XXXXXX
        XXXXX
    XXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        BB BBBBBB
             gettext(u'Edit Location') 
        BBBB
             gettext(u'Add Location') 
        BBBBB
    XXXXX
    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BB BBBBBB
             gettext(u'Update the location details below') 
        BBBB
             gettext(u'Fill in the details to create a new location') 
        BBBBB
    XXXX
XXXXXX

XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    
    BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                XXXXXXXXXXX
            BBBBBB
        XXXXXX
    BBBBB 
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXX X X X X XXXX XXXXXXXXXXX
                    XXXXXX
                     gettext(u'Basic Information') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Enter the location name in different languages') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
                                     gettext(u'English') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
                                     gettext(u'French') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                    XXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXX 
                                XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to French') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                        BB BBBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXX 
                                XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to English') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                        BB BBBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXX X XXXXXXXX XXXXXXXXXXXXXXXX X X XXXXXXXX XXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXX X X XXXX X X X X XXX XXXXXXXXXXX
                    XXXXXX
                     gettext(u'Location Details') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Geographic and category information') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                        XXXXX
                            XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                            XXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBB
                                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                            BB BBBBBBBBBBBBBBBBBBBBBBB
                                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                        XXXXXX
                        XXXXX
                            XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                            XXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBB
                                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                            BB BBBBBBBBBBBBBBBBBBBBBBBB
                                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXX X X XXXXXXXXXX X X XXXXXXXXXXXXX X X XXXXXXXXXXXXXXXX XXXXXXX X X XXXXXXXXXXXXXXX X X XXXX XXXXXXXXXXX
                    XXXXXX
                     gettext(u'Content') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Location story and description') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
                                     gettext(u'English') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
                                     gettext(u'French') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                    XXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXXX 
                                XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to French') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                        BB BBBBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXXX 
                                XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to English') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                        BB BBBBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX X X XXXXX X X X X XXXX XXXXXXXXXXX
                    XXXXXX
                     gettext(u'Operational Details') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Opening hours and pricing information') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                XXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
                    BBB BBBBBBBB BB BBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                            
                            XXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                
                            XXXXXXXX
                        XXXXXX
                    BBBBBB
                XXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXX X XXXXX XXX X X XXXXX X X X X XXXX XXXXXXXXXXX
                    XXXXXX
                     gettext(u'Status & Settings') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Location visibility and features') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX
                    
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        
                    XXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Images') XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Upload images for this location (max 10). Images will be automatically optimized.') XXXX
            XXXXXX
            
            
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                        BB BBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                        XXXXXX
                        BBBBB
                        XXXX XXXXXXXXXXXXXXX
                            
                            XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBB gettext(u'Replace Image') BBBB gettext(u'Upload Image') BBBBB
                            XXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                        XXXXXX
                        BB BBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                
                                XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXX
                            XXXXXXXX
                        XXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                 gettext(u'Add Another Image') 
            XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Cancel') 
        XXXX
        XXXX XXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X XXXXXX X X X XXX XXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX X X XXXXXXXX XXXXXXX XXX X X XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                BB BBBBBB gettext(u'Update Location') BBBB gettext(u'Save Location') BBBBB
            XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXXX

BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        
        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X
    
    XXXXXXXX XXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXX XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX X
                XXXXX XXXXXXXX X XXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX X
                X
            X
        XXX
    XXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX
    XXX
    
    XX XXXXXXX XXXXX XX XXXX XXX XXXX XXXXXX XX XXXX XXXX XXX XXXXXXX XXXXXXXXXXX XX XXXXX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XX XXXXX XXXXX XX XXXXXX XXXXXXX XX XXXXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    XXX

    XX XXXXXX XXXXXXX XXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXX XX XXXXXXXXX X
            XXXXXXXXXXXXXX XXXXXX XX XXXXXX XXXXXXX XXXXXXX
            XXXXXXX
        X
        
        XX XXXXX XXX XXXXX XXXXX XXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXX XXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXX XXX XXXX XXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXX XXXXXXXXXXXXXXX X XXX
        
        XX XXXXXX XXX XXXXXXXX XXXXX XXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXXXX XXXXXXXX XX XXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXXX XXXXX XXXXX
        XXXXXXXXXXXXXXXX X XXXXXXXXX X XX
    XXX
    
    XX XX XXXXXXXXXXX XXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXXXXXXXX XX XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX X
            XXXXX XXXXXXXXX X XXXXXXXXXXX
            
            XX XXXXX XXXXXXX XXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXXX X
                XXX X
                    XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXX
                    
                    XX XXXXXXXXXXXXX XX XXXXXXXXXXXX X
                        XX XXXXXXXX XXXXXX XXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX XX X
                            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXX X XXXXXXXX
                            XXXXXXXXXXXXXXXXXX X XXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX
                    X
                X XXXXX XXXXXXX X
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX
                X
            X
        XXX
    X
XXXXXXXXX
BBBBBBBB BBBBBBBBBBB