BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB
XXXX XXXXX XXX XXXXXXX XXXXXXXXX XXX
BBBBB BBBBB gettext(u'Locations List') BBBBBBBB BBBBB

BBBBB BBBB
   XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
         XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXX XX XXXXXXXXXXXXXXXXX XXX XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXX XX XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX XXX XX XXXXXXX XXXXXXXXXXXXXXXXXXX
          gettext(u'List')  
      XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
         XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          gettext(u'Add') 
      XXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
         XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX X X X XXXXXX XXXXX XXXXX X X X XXXXX X XXXXXX X X X XXXXXXXXXXXX XXXXXX X X X X X XXXXXX X X X X XXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXX
          gettext(u'Categories') 
      XXXXXXXXX
   XXXXXX
   BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

   XXXX XXXXXXXXXXXXXXXX XXXXXX
      
      XXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX
    XXXX
        XXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                 gettext(u'Location') 
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XX X X XXXXXXXXXXXXX XXXX
                XXXXXX
            XXXXXXX
        XXXXX
        XXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                 gettext(u'Category') 
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XX X X XXXXXXXXXXXXX XXXX
                XXXXXX
            XXXXXXX
        XXXXX
        XXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                 gettext(u'City') 
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XX X X XXXXXXXXXXXXX XXXX
                XXXXXX
            XXXXXXX
        XXXXX
        XXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                 gettext(u'Country') 
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XX X X XXXXXXXXXXXXX XXXX
                XXXXXX
            XXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                 gettext(u'Email') 
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XX X X XXXXXXXXXXXXX XXXX
                XXXXXX
            XXXXXXX
        XXXXX
        XXXXXXXXX XXXXX
XXXXXXXX
        XXXXXXX
    BBB BBBB BB BBBBBBBBB
       XXXX
             XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXX
             XXXXXXXXX
             XXXXXXXXX
             
             XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                FFFFFFFFFFFF
             XXXXX

             XXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                   XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX  XXXXXXXXXX X XXX XXXXX
                         XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXX XXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXXX XXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXX XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXX XXXXXXX XXXXXXXXX XXX XX XXXXX XX XXXXXX XXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXXXX XXXXX XXXXX XXX XXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXX
                      XXXXXX
                       gettext(u'Edit') 
                   XXXX
                   XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXX XXXXX
                         XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XX XX XXXXX XX XXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXX XXXXX XX XXX XXXXXX XXXXXXXX XXXXXXXXXX XXXX XXXXX XX XXXXX XXXXXXXX XXXXXXXX XX XXXXX XXXX XXXXX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXX
                      XXXXXX
                       gettext(u'Delete') 
                   XXXXXXXXX
                XXXXXX
             XXXXX
       XXXXX
       BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
    BBBBBB
XXXXXXXX
      XXXXXXXX

   XXXXXX
BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
   XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXXXX

   XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX X
      XXXXX XXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
         XXXXXXXXXXX XXXXX
         XXXXXXXXXXXXXX XXXXX
      XXX
   X
   XXXXXXXXX
BBBBBBBB BBBBBBBBBBB