BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Pages List') BBBBBBBB BBBBB

BBBBB BBBB
   XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
         XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
          gettext(u'List')  
      XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
         XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          gettext(u'Add') 
      XXXX
   XXXXXX

   XXXX XXXXXXXXXXXXXXXX XXXXXX
      
      XXXXXX XXXXXXXXXXXXXXX
         XXXXXXX
            XXXX
                  XXXX
                     XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Title') 
                        XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                              XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XX X X XXXXXXXXXXXXX XXXX
                        XXXXXX
                     XXXXXXX
                  XXXXX
                  XXXX
                     XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Slug') 
                        XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                              XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XX X X XXXXXXXXXXXXX XXXX
                        XXXXXX
                     XXXXXXX
                  XXXXX
                  XXXX
                     XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Status') 
                        XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                              XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XX X X XXXXXXXXXXXXX XXXX
                        XXXXXX
                     XXXXXXX
                  XXXXX
                  XXXX
                     XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Created At') 
                        XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                              XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XX X X XXXXXXXXXXXXX XXXX
                        XXXXXX
                     XXXXXXX
                  XXXXX
                  XXXXXXXXX
            XXXXX
         XXXXXXXX
         XXXXXXX
            BBB BBBB BB BBBBB
               XXXX
                     XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXX
                     XXXX
                        BB BBBBBBBBBBBBBB
                           XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Active') XXXXXXX
                        BBBB
                           XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Inactive') XXXXXXX
                        BBBBB
                     XXXXX
                     XXXXFFFFFFFFFFFFXXXXX
                     XXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                           XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                              XXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX  XXXXXXXXXX X XXX XXXXX
                                 XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXX XXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXXX XXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXX XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXX XXXXXXX XXXXXXXXX XXX XX XXXXX XX XXXXXX XXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXXXX XXXXX XXXXX XXX XXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXX
                              XXXXXX
                               gettext(u'Edit') 
                           XXXX
                           XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                              XXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXX XXXXX
                                 XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XX XX XXXXX XX XXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XXXXX XXXXX XX XXX XXXXXX XXXXXXXX XXXXXXXXXX XXXX XXXXX XX XXXXX XXXXXXXX XXXXXXXX XX XXXXX XXXX XXXXX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXX XXX XXXXXXX XXXXXXXXX XXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXX
                              XXXXXX
                               gettext(u'Delete') 
                           XXXXXXXXX
                        XXXXXX
                     XXXXX
               XXXXX
               BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
            BBBBBB
         XXXXXXXX
      XXXXXXXX

   XXXXXX
BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
   XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXXXX

   XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX X
      XXXXX XXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
         XXXXXXXXXXX XXXXX
         XXXXXXXXXXXXXX XXXXX
      XXX
   X
   XXXXXXXXX
BBBBBBBB BBBBBBBBBBB