# Generated by Django 5.2.9 on 2026-04-22 10:14

import django.db.models.deletion
import guard.models
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ad Click Record',
                'verbose_name_plural': 'Ad Click Records',
            },
        ),
        migrations.CreateModel(
            name='ArHistoricalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('marker_image', models.ImageField(help_text='Image representing the real world site for recognition', upload_to=guard.models.ar_marker_path, verbose_name='Marker Image (The real world target)')),
                ('historical_asset', models.FileField(help_text='.glb or .usdz file containing the historical reconstruction', upload_to=guard.models.ar_asset_path, verbose_name='3D Model or Historical Overlay')),
                ('description', models.TextField(blank=True, verbose_name='Historical Description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AR Historical Content',
                'verbose_name_plural': 'AR Historical Contents',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ad', 'Ad'), ('event', 'Event')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_locations', models.IntegerField(default=0)),
                ('locations_this_month', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('upcoming_events', models.IntegerField(default=0)),
                ('events_this_month', models.IntegerField(default=0)),
                ('total_hikings', models.IntegerField(default=0)),
                ('hikings_this_month', models.IntegerField(default=0)),
                ('total_ads', models.IntegerField(default=0)),
                ('active_ads', models.IntegerField(default=0)),
                ('total_fcm_devices', models.IntegerField(default=0)),
                ('ios_devices', models.IntegerField(default=0)),
                ('android_devices', models.IntegerField(default=0)),
                ('active_users_30d', models.IntegerField(default=0)),
                ('notifications_sent_24h', models.IntegerField(default=0)),
                ('notifications_failed_24h', models.IntegerField(default=0)),
                ('error_count_24h', models.IntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dashboard Statistics',
                'verbose_name_plural': 'Dashboard Statistics',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('endDate', models.DateField(verbose_name='End Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('link', models.URLField(verbose_name='The link to subscribe')),
                ('short_link', models.URLField(blank=True, null=True)),
                ('short_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='Description')),
                ('description_fr', tinymce.models.HTMLField(null=True, verbose_name='Description')),
                ('boost', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('clicks', models.IntegerField(default=0)),
                ('reminder_status', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
            },
        ),
        migrations.CreateModel(
            name='EventClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Click Record',
                'verbose_name_plural': 'Event Click Records',
            },
        ),
        migrations.CreateModel(
            name='Hiking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Hiking',
                'verbose_name_plural': 'Hikings',
            },
        ),
        migrations.CreateModel(
            name='HikingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImageAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ad Image',
                'verbose_name_plural': 'Ad Images',
            },
        ),
        migrations.CreateModel(
            name='ImageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
            },
        ),
        migrations.CreateModel(
            name='ImageHiking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hiking Image',
                'verbose_name_plural': 'Hiking Images',
            },
        ),
        migrations.CreateModel(
            name='ImageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Location Image',
                'verbose_name_plural': 'Location Images',
            },
        ),
        migrations.CreateModel(
            name='LegacyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Image')),
                ('link', models.URLField(verbose_name='Link')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active_ads', models.BooleanField(default=False, verbose_name='Active Ads')),
                ('story', tinymce.models.HTMLField(verbose_name='Story')),
                ('story_en', tinymce.models.HTMLField(null=True, verbose_name='Story')),
                ('story_fr', tinymce.models.HTMLField(null=True, verbose_name='Story')),
                ('openFrom', models.TimeField(blank=True, help_text='Add opening hours if the location is open from a specific time', null=True, verbose_name='Open From')),
                ('openTo', models.TimeField(blank=True, help_text='Add opening hours if the location is open to a specific time', null=True, verbose_name='Open To')),
                ('admissionFee', models.DecimalField(blank=True, decimal_places=2, help_text='Add admission fee if the location has a specific admission fee', max_digits=10, null=True, verbose_name='Admission Fee')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Category',
                'verbose_name_plural': 'Location Categories',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('device_count_attempted', models.IntegerField(default=0)),
                ('device_count_succeeded', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
            },
        ),
        migrations.CreateModel(
            name='PublicTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('busNumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='Line Number')),
                ('is_return_journey', models.BooleanField(default=False, help_text='Check this box if this is a return journey', verbose_name='Is Return Journey')),
            ],
            options={
                'verbose_name': 'Public Transport',
                'verbose_name_plural': 'Public Transports',
            },
        ),
        migrations.CreateModel(
            name='PublicTransportTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(verbose_name='Departure Time')),
                ('returnTime', models.TimeField(blank=True, null=True, verbose_name='Return Time')),
            ],
            options={
                'verbose_name': 'Public Transport Time',
                'verbose_name_plural': 'Public Transport Times',
            },
        ),
        migrations.CreateModel(
            name='PublicTransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Public Transport Type',
                'verbose_name_plural': 'Public Transport Types',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(upload_to='sponsors/', verbose_name='Image')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'sponsor',
                'verbose_name_plural': 'sponsors',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', tinymce.models.HTMLField()),
                ('description_en', tinymce.models.HTMLField(null=True)),
                ('description_fr', tinymce.models.HTMLField(null=True)),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tips',
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], unique=True, verbose_name='Day')),
            ],
            options={
                'verbose_name': 'Weekday',
                'verbose_name_plural': 'Weekdays',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='GuardUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la pub')),
                ('image_mobile', models.ImageField(blank=True, help_text='Taille : 320x50 pixels', null=True, upload_to='ads/mobile/', verbose_name='Image Mobile (320x50)')),
                ('image_tablet', models.ImageField(blank=True, help_text='Taille : 728x90 pixels', null=True, upload_to='ads/tablet/', verbose_name='Image Tablette (728x90)')),
                ('link', models.URLField(verbose_name='Lien')),
                ('short_link', models.URLField(blank=True, null=True)),
                ('short_id', models.CharField(blank=True, max_length=50, null=True)),
                ('clicks', models.IntegerField(default=0)),
                ('db_clicks_count', models.IntegerField(default=0)),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payée')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('active', 'Active'), ('finished', 'Terminée')], db_index=True, default='pending_payment', max_length=20, verbose_name='Statut')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='cities_light.city', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Pub',
                'verbose_name_plural': 'Pubs',
                'ordering': ['-created_at'],
            },
        ),
    ]
