# Generated by Django 5.2.9 on 2026-04-22 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
        ('guard', '0001_initial'),
        ('partners', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='shared.userprofile', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='ad',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='cities_light.country', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='adclick',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_records', to='guard.ad'),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='cities_light.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='shared.userprofile', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='guard.eventcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='eventclick',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_records', to='guard.event'),
        ),
        migrations.AddField(
            model_name='hiking',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hikings', to='cities_light.city', verbose_name='Cities'),
        ),
        migrations.AddField(
            model_name='hikinglocation',
            name='hiking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guard.hiking'),
        ),
        migrations.AddField(
            model_name='imagead',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guard.ad'),
        ),
        migrations.AddField(
            model_name='imageevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guard.event'),
        ),
        migrations.AddField(
            model_name='imagehiking',
            name='hiking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guard.hiking'),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='cities_light.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='cities_light.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='location',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_locations', to='partners.partner', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='legacypartner',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='legacy_partners', to='guard.location', verbose_name='Locations'),
        ),
        migrations.AddField(
            model_name='imagelocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guard.location'),
        ),
        migrations.AddField(
            model_name='hikinglocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guard.location'),
        ),
        migrations.AddField(
            model_name='hiking',
            name='locations',
            field=models.ManyToManyField(through='guard.HikingLocation', to='guard.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='guard.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='arhistoricalcontent',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_contents', to='guard.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='guard.locationcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='publictransport',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_transports', to='cities_light.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='publictransport',
            name='fromCity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_city_trips', to='cities_light.city', verbose_name='From City'),
        ),
        migrations.AddField(
            model_name='publictransport',
            name='fromRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_region_trips', to='cities_light.subregion', verbose_name='From Region'),
        ),
        migrations.AddField(
            model_name='publictransport',
            name='toCity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_city_trips', to='cities_light.city', verbose_name='To City'),
        ),
        migrations.AddField(
            model_name='publictransport',
            name='toRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_region_trips', to='cities_light.subregion', verbose_name='To Region'),
        ),
        migrations.AddField(
            model_name='publictransporttime',
            name='publicTransport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicTransportTimes', to='guard.publictransport', verbose_name='Public Transport'),
        ),
        migrations.AddField(
            model_name='publictransport',
            name='publicTransportType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_transports', to='guard.publictransporttype', verbose_name='Public Transport Type'),
        ),
        migrations.AddField(
            model_name='tip',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='cities_light.city', verbose_name='Cities'),
        ),
        migrations.AddField(
            model_name='location',
            name='closedDays',
            field=models.ManyToManyField(blank=True, related_name='locations', to='guard.weekday', verbose_name='Closed Days'),
        ),
        migrations.AlterUniqueTogether(
            name='hikinglocation',
            unique_together={('hiking', 'location')},
        ),
    ]
