# Generated by Django 5.2.9 on 2026-02-18 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
        ('guard', '0055_event_boost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publictransporttype',
            options={'ordering': ['name'], 'verbose_name': 'Public Transport Type', 'verbose_name_plural': 'Public Transport Types'},
        ),
        migrations.AddField(
            model_name='publictransport',
            name='fromCity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_city_trips', to='cities_light.city', verbose_name='From City'),
        ),
        migrations.AddField(
            model_name='publictransport',
            name='toCity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_city_trips', to='cities_light.city', verbose_name='To City'),
        ),
        migrations.AddField(
            model_name='publictransporttype',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='publictransporttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publictransporttype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='publictransporttype',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='publictransporttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publictransport',
            name='busNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='publictransport',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='publictransport',
            name='fromRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_region_trips', to='cities_light.subregion', verbose_name='From Region'),
        ),
        migrations.AlterField(
            model_name='publictransport',
            name='publicTransportType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_transports', to='guard.publictransporttype', verbose_name='Transport Type'),
        ),
        migrations.AlterField(
            model_name='publictransport',
            name='toRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_region_trips', to='cities_light.subregion', verbose_name='To Region'),
        ),
        migrations.AlterField(
            model_name='publictransporttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publictransporttype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publictransporttype',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
