# Generated by Django 5.2.9 on 2026-02-21 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
        ('guard', '0056_alter_publictransporttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publictransporttype',
            options={'verbose_name': 'Public Transport Type', 'verbose_name_plural': 'Public Transport Types'},
        ),
        migrations.RemoveField(
            model_name='publictransporttype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='publictransporttype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='publictransporttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publictransporttype',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='publictransporttype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='publictransporttime',
            name='returnTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Return Time'),
        ),
        migrations.AlterField(
            model_name='publictransport',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_transports', to='cities_light.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='publictransport',
            name='publicTransportType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_transports', to='guard.publictransporttype', verbose_name='Public Transport Type'),
        ),
        migrations.AlterField(
            model_name='publictransporttime',
            name='time',
            field=models.TimeField(verbose_name='Departure Time'),
        ),
        migrations.AlterField(
            model_name='publictransporttype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publictransporttype',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publictransporttype',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
