# Generated by Django 5.2.9 on 2026-03-02 08:53

import django.db.models.deletion
import guard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0057_alter_publictransporttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='publictransport',
            name='is_return_journey',
            field=models.BooleanField(default=False, help_text='Check this box if this is a return journey', verbose_name='Is Return Journey'),
        ),
        migrations.CreateModel(
            name='ArHistoricalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('marker_image', models.ImageField(help_text='Image representing the real world site for recognition', upload_to=guard.models.ar_marker_path, verbose_name='Marker Image (The real world target)')),
                ('historical_asset', models.FileField(help_text='.glb or .usdz file containing the historical reconstruction', upload_to=guard.models.ar_asset_path, verbose_name='3D Model or Historical Overlay')),
                ('description', models.TextField(blank=True, verbose_name='Historical Description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_contents', to='guard.location')),
            ],
            options={
                'verbose_name': 'AR Historical Content',
                'verbose_name_plural': 'AR Historical Contents',
            },
        ),
    ]
