# Generated by Django 5.2.9 on 2026-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0060_adclick_eventclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
