# Generated by Django 5.2.9 on 2026-03-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0061_event_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ad', 'Ad'), ('event', 'Event')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
