# Generated by Django 5.2.9 on 2026-03-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
        ('guard', '0062_click'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pub', 'verbose_name_plural': 'Pubs'},
        ),
        migrations.AddField(
            model_name='ad',
            name='db_clicks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('active', 'Active'), ('finished', 'Terminée')], db_index=True, default='pending_payment', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='cities_light.city', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='cities_light.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Taille : 320x50 pixels', null=True, upload_to='ads/mobile/', verbose_name='Image Mobile (320x50)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_tablet',
            field=models.ImageField(blank=True, help_text='Taille : 728x90 pixels', null=True, upload_to='ads/tablet/', verbose_name='Image Tablette (728x90)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Payée'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.URLField(verbose_name='Lien'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la pub'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
