# Generated by Django 5.2.9 on 2026-04-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0064_location_partner_partner_created_at_partner_email_and_more'),
    ]

    operations = [
    ]
