# Generated by Django 5.2.9 on 2026-04-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0067_fix_location_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='partner',
        ),
        migrations.AddField(
            model_name='partner',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='partners', to='guard.location', verbose_name='Locations'),
        ),
    ]
