# Generated by Django 5.2.9 on 2026-04-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0068_remove_location_partner_partner_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_locations', to='guard.partner', verbose_name='Partner'),
        ),
    ]
