# Generated by Django 5.2.9 on 2026-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0069_location_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
            },
        ),
        migrations.CreateModel(
            name='DashboardStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_locations', models.IntegerField(default=0)),
                ('locations_this_month', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('upcoming_events', models.IntegerField(default=0)),
                ('events_this_month', models.IntegerField(default=0)),
                ('total_hikings', models.IntegerField(default=0)),
                ('hikings_this_month', models.IntegerField(default=0)),
                ('total_ads', models.IntegerField(default=0)),
                ('active_ads', models.IntegerField(default=0)),
                ('total_fcm_devices', models.IntegerField(default=0)),
                ('ios_devices', models.IntegerField(default=0)),
                ('android_devices', models.IntegerField(default=0)),
                ('active_users_30d', models.IntegerField(default=0)),
                ('notifications_sent_24h', models.IntegerField(default=0)),
                ('notifications_failed_24h', models.IntegerField(default=0)),
                ('error_count_24h', models.IntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dashboard Statistics',
                'verbose_name_plural': 'Dashboard Statistics',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('device_count_attempted', models.IntegerField(default=0)),
                ('device_count_succeeded', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
            },
        ),
    ]
