# Generated by Django 5.2.9 on 2026-04-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0072_remaining_from_0071'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarduser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
