# Generated by Django 5.2.9 on 2026-03-28 22:15

import advertisements.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file_type',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to=advertisements.models.advertisement_upload_path, validators=[advertisements.models.validate_image_file], verbose_name='Image / GIF'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom de la publicité'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='redirect_url',
            field=models.URLField(max_length=500, verbose_name='URL de redirection'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de validation'), ('REVIEW', 'En révision'), ('ACTIVE', 'Active'), ('PAUSED', 'En pause'), ('REJECTED', 'Rejetée'), ('EXPIRED', 'Expirée')], default='PENDING', max_length=20),
        ),
    ]
