BBBB BBBB

XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX
                XXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX
                     gettext(u'Name') 
                XXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBBB BB BBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    
                XXXXX
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX
XXXXXX
