XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXXXX
        XXXX X XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXX XX XXXXXXXX XX X
        XXXXXXXXXX X XXXXXXXXXX XXXXXX XXXXXXX XXXX XXXXX XXXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXX X XXXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXX X
        XXXXXXX X XXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXX X
        XXXXXXXXX X XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXX X
        XXXXXXXXXXXX X XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXX X
        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX XXXX X XX
            XXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXX X X XXX XX X
        XXXXXXXXXXXXX X X XXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XX X
    XXXXXXXX
XXXXXXX
XXXXXX
BBBB BBBB BBBBBB

XXXX XXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXX
        XXXX gettext(u'Vérification de votre compte') XXXXX
        XXX gettext(u'Activation du compte partenaire') XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX
        XXX gettext(u'Bonjour <strong>%(company_name)s</strong>,') SSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXX
        XXX gettext(u'Merci de vous être inscrit sur notre plateforme de gestion de partenaires.') XXXX

        BB BBBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX X XXX XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Vos identifiants de connexion :') XXXX
            BB BBBBBBBB
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u"Nom d'utilisateur :") XXXXXXXXX XXXX
            BBBBB
            BB BBBBBBBB
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Mot de passe :') XXXXXXXXX XXXX
            BBBBB
            XX XXXXXXXXXXXXXXXXX X X XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Conservez ces informations en lieu sûr.') XXXX
        XXXXXX
        BBBBB

        XXX gettext(u'Pour activer votre compte, veuillez cliquer sur le lien ci-dessous :') XXXX
        XXX
            XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
        XX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXXXXX
             gettext(u'Ce lien de sécurité expirera dans <span class="emphasis">24 heures</span>.') SS SSSS SS SSSSSSSS SSSSSSSS SSSS SSSSS SSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSS
        XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX
        XXX gettext(u'&copy; 2026 FielMedina. Tous droits réservés.') XXXX
        XXX gettext(u"Si vous n'êtes pas à l'origine de cette demande, vous pouvez ignorer cet email.") XXXX
    XXXXXX

XXXXXX
XXXXXXX
XXXXXXX