XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX
        XX XXXXXXXXXX XXXXXXXX X XXXXXXX XX XXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXX X

        XXXXX X
            XXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXX XXXXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
        X

        XXXX X
            XXXXXXX XXXXX
        X

        XXXX X
            XXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
        X

        XX XXXXXXXX XXXXXXXXXX XX
        XXX X
            XXXXXXXXX XXXXXX
            XXXXXX XX
            XXXXXXXX XX
        X
        XXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXXXXX
            XXXX XXXXX
            XXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
        X
        XXXXXXXXXX XXXXXXX X
            XX X XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX X
            XXXX X XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX X
        X

        XX XXXX XXXXX XX
        XXXXX X
            XXXXXXXXX XXXXXX
            XXXXXX XX
            XXXXXXXXXXXXXXXXX 
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX
                XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXX XXXXX
            XXXXXXXX XX
        X

        XXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXXXX XX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXX XX XXXX XX XXXXXXXXX
            XXXXXXXX XX
        X
        XXXXXXXXXX XXXXXX X
            XXXX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XX   X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXX X
        X

        XX XXXX XX
        XXXXXXXXXX X
            XXXXXX XXXXXX
            XXXXXXX XXXXXX
            XXXXXXX X XXXX XXXXX
            XXXXXXXXX XXXXXXXXX
        X
        XXXXXXXXXXXX X
            XXXXXX XXXXXX
            XXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXX XX XXXX XXXXX
        X
        XXXXXXXXXX XXXXXXX X
            XXXX X XXXXXXXXXX XXXXXXXXX XXXXXXXX XX X
            XX   X XXXXXXXXXX XXXXXXXXX XXXXXXXX XX X
        X
        XXXXXXXXXXXX XXX X
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXX XXXX
            XXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXXX
        X
        XXXXXXXXXXXX XXX XXXX X
            XXXXXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXXX XXXX
            XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXX
        X
        XXXXXXXXXX XXXXXXXXX X
            XX X XXXXXXXXXXXXXXXXXX XX X
        X

        XX XXXX XXXX XX
        XXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXX
            XXXXXXXX XX
            XXXXXXXXXX XXXX XX XXXXXXXX XX XXXXXXXXX
        X
        XXXXXXXXXX XXXX X
            XX   X XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXX X
            XXXX X XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XX X
        X

        XX XXXX XX
        XXXXX X
            XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XX
            XXXXXXXXXX XXXXXX XXXX XXXX XXXX XXXXXXXXX
        X

        XX X
            XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
        X

        XXXXX X
            XXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        X

        X X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXX XXXXX
            XXXXXXXXXXXX XXXX
        X

        XX XXXXXXX XX
        XXXXXXXX X
            XXXXXX XXXXX
            XXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXX XXXX XXXXX
        X

        XX XXXX XX
        XXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXX XXXXX
            XXXXXXXXXXX XXXXX
        X
        XXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXX
            XXXXXXXX XXXX XX
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXX X
        XXXXXXXXXX XXXX X
            XXXXXX XXXX
            XXXXXXX XXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX XX
        X

        XXXX X
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXX
        X
        XXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXX
            XXXXXXXXXXXXXXX XXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXX XXXX XXXX XXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXX XXXXXX XXXXXXXXXX X XXX XXXXXXX XXXX XXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXX XX XX XXXXXXXXXX XXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XX XXXXXXXXXXXXXXXX
        XXXXXX

        XX XXXXXXXX XXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXX XXXXX

        XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXX X XXXX XXXXXX XXXXXXXXXXXXXX
    XXXXXX
XXXXXXX
XXXXXXX