BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB
     BB BBBBBB
           gettext(u'Edit Public Transport') 
     BBBB
           gettext(u'Add Public Transport') 
     BBBBB
BBBBBBBB BBBBB

BBBBB BBBB
XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXX XXXXXXX X X XXXXXXXX XXXX XXX X X XXXXXXX XXXXXXX XXXXXXXXXXX X X XXX XXXXX X X XXXXXXXXXX X X XXXXXXXXX X X XXX XXXXX X X XXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Dashboard') 
            XXXX
        XXXXX
        XXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Public Transports') XXXX
            XXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBB gettext(u'Edit') BBBB gettext(u'Add') BBBBB
                XXXXXXX
            XXXXXX
        XXXXX
    XXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        BB BBBBBB gettext(u'Edit Public Transport') BBBB gettext(u'Add Public Transport') BBBBB
    XXXXX
    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BB BBBBBB gettext(u'Update the transport route details below') BBBB gettext(u'Fill in the details to create a new transport route') BBBBB
    XXXX
XXXXXX

XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                XXXXXXXXXXX
            BBBBBB
        XXXXXX
    BBBBB

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXX X X X X XXXX XXXXXXXXXXX
                    XXXXXX
                     gettext(u'Transport Details') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Select the transport type and city') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX
                            
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXX
                            XXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                
                            XXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                
                            XXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXX XX XXXX XXXXXXX XXXXXX X XXXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXX XXX XXXX XXXXXXXXXXXXXXXX
                    XXXXXX
                     gettext(u'Route') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Select departure and arrival cities') XXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XX XXXXXX XXXXXXX XXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXX XXX XXXX XXXXXXXXXXXXXXXX
                    XXXXXX
                     gettext(u'Local Route') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Select the departure and arrival regions') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXX XXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX X X XXXXX X X X X XXXX XXXXXXXXXXX
                    XXXXXX
                     gettext(u'Departure Times') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Add the departure times for this route') XXXX
            XXXXXX
            
            
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                BBB BBBBBBBBB BB BBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    
                    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX
                        XXXXX
                            XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                 gettext(u'Departure Time') 
                            XXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                        XXXXXX
                        XXXXX
                            XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                 gettext(u'Return Time') 
                            XXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                        XXXXXX
                    XXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            
                            XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXX
                        XXXXXXXX
                    XXXXXX
                    BBBB
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXX X X XXXXXXXX XXXXXXXXXX X X XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX X X XXXXXXXXXXX X X XXXX XXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                    BBBBB
                XXXXXX
                BBBBBB
            XXXXXX

            XXXX XXXXXXXX XXX XXX XXXX XXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                    
                    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX
                        XXXXX
                            XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                 gettext(u'Departure Time') 
                            XXXXXXXX
                            
                        XXXXXX
                        XXXXX
                            XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                 gettext(u'Return Time') 
                            XXXXXXXX
                            
                        XXXXXX
                    XXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXX X X XXXXXXXX XXXXXXXXXX X X XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX X X XXXXXXXXXXX X X XXXX XXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXXX
            XXXXXXXXXXX
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                 gettext(u'Add Another Time') 
            XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Cancel') 
        XXXX
        XXXX XXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X XXXXXX X X X XXX XXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX X X XXXXXXXX XXXXXXX XXX X X XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                BB BBBBBB gettext(u'Update Transport') BBBB gettext(u'Save Transport') BBBBB
            XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXXX

BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
XXXXXXX
    XXXXXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXX XXXX XXXXXXXXX
    X
    XXXXXXXXXX XXXXXX X
        XXXX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        XX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXX X
    X
XXXXXXXX
XXXXXXXX

XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX

XX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXX XXXXXXXX X
    XX XXXXX XXXXXXX
    XXXXXXXXXXXXXXXX X XXXXXXX X XXXXXXX X XXXXXXX
X

XX XXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX

    XX XXXX XXX XXXXXXXXXXX XXXXXXXX XX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX

    XX XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX

    X XXXX XX XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX

    X XXXX XX XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    X
X

XX XXX XXXXXX XXXXXXXXX XXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXX X
    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X XXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X XXX
X

XX XXX XXXXXXXXXX XXXX XXXX XXX XXX XXXXXX XXXX
XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
    XX XXXXXXXX XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX XXXXXXX
    XXX X
        XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXXXXX X XXXXXXXX XXXXXX XX X
                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XX X
                    XXXXX XXXXXX X XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                XXX
                XXXXXXXXXXXX X XXXXXXXXXXXXX
            XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        X
    X XXXXX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXX
    X
X

XX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XX XXXXXXXXX XXXX XXXXXX X XXXXXXX XXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXXXXXXXXXXXXXXXXXXX
    XX XXXXX XXXXXX XXXX XXXXXXXXX XXXXX XX XXXXX XXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXX
XXX

XX XXXX XXXX XXXXXXX X XXXXXX XXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
    XX XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
XXX

XX XXXXXX XXXXXX XXXXXXXXX XXXXXX XXX XXXXX XXXXXXX XXXX XXX XX XXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
    XX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX
    X
XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
    XX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX
    X
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
    XX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXX
    X
XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
    XX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXX
    X
XXX

XX XXX XXXXXXX XXX XX XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
XX XXXXXXXXXXXXXXXXXXX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
    XX XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
X

XX XXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XX XXXX XXXXXX XXX XX XXXX XXX XXXXXXXXXX XXXX XXXXX
XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXX XXXXXXXXXXXXXXX X XXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXX X
            XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX
        X
    XXX
XX

XX XXXX XXXXXXXX XXXXXX XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX

XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXX XXXXXXX

        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX X XX
        
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
X

XXXXXXXX XXXXXXXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
    
    XXXXXXXXXXXXXXXXXX XXXXXX XX X
        XXXXX XXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XX X
            XX XXXXXXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXX XXXXX X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            X
        XXX
    XXX
X

XXXXXXXXX
BBBBBBBB BBBBBBBBBBB
