BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Public Transports List') BBBBBBBB BBBBB

BBBBB BBBB

XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX

   XXXX XXXXX XXXX X XXX XXX
   XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX
         XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
         X XXXX
      XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
         XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
         X XXX
      XXXX
   XXXXXX

  

XXXXXX

XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
   XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX 
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
      X  gettext(u'All') 
   XXXX
   XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXX
      X  gettext(u'Bus') 
   XXXX
   XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXX
      X  gettext(u'Train') 
   XXXX
   XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXX
      X  gettext(u'Metro') 
   XXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX

XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
   XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
      XXXX
         XXX XXXXXXXXXXX XXXXXX gettext(u'Type') XXXXX
         XXX XXXXXXXXXXX XXXXXX gettext(u'Number') XXXXX
         XXX XXXXXXXXXXX XXXXXX gettext(u'From') XXXXX
         XXX XXXXXXXXXXX XXXXXX gettext(u'To') XXXXX
         XXX XXXXXXXXXXX XXXXXX gettext(u'Times') XXXXX
         XXX XXXXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Actions') XXXXX
      XXXXX
   XXXXXXXX

   XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX

   BBB BBBB BB BBBBBBBBBB
   XXX XXXXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXX XXX
      XXX XXXXXXXXXXX XXXXXX
         BB BBBBBBBBBBBBBBBBBBBBBBBB
            BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
               BB BBBBBBB BB BBBB
                  XXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                     X 
                  XXXXXXX
               BBBB BBBBBBB BB BBBB
                  XXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                     X 
                  XXXXXXX
               BBBB BBBBB BB BBBB
                  XXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                     X 
                  XXXXXXX
               BBBB
                  
               BBBBB
            BBBBBBB
         BBBB
            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
         BBBBB
      XXXXX

      XXXX XXXXXX XXX
      XXX XXXXXXXXXXX XXXXXX
         BB BBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX
               FFFFFFFFFFF
            XXXXXXX
         BBBB
            X
         BBBBB
      XXXXX

      XXXX XXXX XXX
      XXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
         BB BBBBBBBBBBBBBBBBBBBBBBBB
            BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
               BB BBBBBBB BB BBBB
                  BB BBBBBBBBBBBBBBBBBXBBBBB
               BBBB BBBBBBB BB BBBB
                  BB BBBBBBBBBBBBB
                  BBBB BBBBBBBBBBBBBBB
                  BBBBXBBBBB
               BBBB
                  BB BBBBBBBBBBBBBBBBBBBXBBBBB
               BBBBB
            BBBBBBB
         BBBBXBBBBB
      XXXXX

      XXXX XX XXX
      XXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
         BB BBBBBBBBBBBBBBBBBBBBBBBB
            BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
               BB BBBBBBB BB BBBB
                  BB BBBBBBBBBBBBBBBXBBBBB
               BBBB BBBBBBB BB BBBB
                  BB BBBBBBBBBBB
                  BBBB BBBBBBBBBBBBB
                  BBBBXBBBBB
               BBBB
                  BB BBBBBBBBBBBBBBBBBXBBBBB
               BBBBB
            BBBBBBB
         BBBBXBBBBB
      XXXXX

      XXXX XXXXX XXX
      XXX XXXXXXXXXXX XXXXXX
         XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
            BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
               XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                  X FFFFFFFFFF
                  BB BBBBBBBBBBBBBBB
                     XXXXX XXXXXXXXXXXXXXXXXXXXX
                     XXXXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
                  BBBBB
               XXXXXXX
            BBBBB
               XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'No times') XXXXXXX
            BBBBBB
         XXXXXX
      XXXXX

      XXXX XXXXXXX XXX
      XXX XXXXXXXXXXX XXXX XXXXXXXXXXXX
         XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX

            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX 
               XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
               X  gettext(u'Edit') 
            XXXX

            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
               X  gettext(u'Delete') 
            XXXXXXXXX

         XXXXXX
      XXXXX

   XXXXX

   BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
   BBBBBB

   XXXXXXXX
XXXXXXXX

XXXXXX

BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX X
   XXXXX XXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXXX
   XXX
X
XXXXXXXXX
BBBBBBBB BBBBBBBBBBB