BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB
     BB BBBBBB
           gettext(u'Edit Tip') 
     BBBB
           gettext(u'Add Tip') 
     BBBBB
BBBBBBBB BBBBB

BBBBB BBBB
XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX X X XXXXXXXX XXXX XXX X X XXXXXXX XXXXXXX XXXXXXXXXXX X X XXX XXXXX X X XXXXXXXXXX X X XXXXXXXXX X X XXX XXXXX X X XXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Dashboard') 
            XXXX
        XXXXX
        XXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Tips') XXXX
            XXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBB gettext(u'Edit') BBBB gettext(u'Add') BBBBB
                XXXXXXX
            XXXXXX
        XXXXX
    XXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        BB BBBBBB
             gettext(u'Edit Tip') 
        BBBB
             gettext(u'Add Tip') 
        BBBBB
    XXXXX
    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BB BBBBBB
             gettext(u'Update the tip details below') 
        BBBB
             gettext(u'Fill in the details to create a new tip') 
        BBBBB
    XXXX
XXXXXX

XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    
    BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                XXXXXXXXXXX
            BBBBBB
        XXXXXX
    BBBBB 
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXX X X X X XXXX XXXXXXXXXXX
                    XXXXXX
                     gettext(u'Tip Information') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Select the city and enter the tip description') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXX
                XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                XXXXXXXX
                
                BB BBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX

            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
                                     gettext(u'English') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
                                     gettext(u'French') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                    XXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX 
                                XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to French') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX 
                                XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to English') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Cancel') 
        XXXX
        XXXX XXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X XXXXXX X X X XXX XXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX X X XXXXXXXX XXXXXXX XXX X X XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                BB BBBBBB gettext(u'Update Tip') BBBB gettext(u'Save Tip') BBBBB
            XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXXX

BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        
        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X

    XX XX XXXXXXXXXXX XXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXX
BBBBBBBB BBBBBBBBBBB
