BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB
BB BBBBBB
 gettext(u'Edit Event') 
BBBB
 gettext(u'Add Event') 
BBBBB
BBBBBBBB BBBBB

BBBBB BBBB
XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXXXXXXXX XXXXXXX X X XXXXXXXX XXXX XXX X X XXXXXXX XXXXXXX XXXXXXXXXXX X X XXX XXXXX X X XXXXXXXXXX X X XXXXXXXXX X X XXX XXXXX X X XXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
                XXXXXX
                 gettext(u'Dashboard') 
            XXXX
        XXXXX
        XXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX
                    XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Events') XXXX
            XXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBB gettext(u'Edit') BBBB gettext(u'Add') BBBBB
                XXXXXXX
            XXXXXX
        XXXXX
    XXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        BB BBBBBB
         gettext(u'Edit Event') 
        BBBB
         gettext(u'Add Event') 
        BBBBB
    XXXXX
    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BB BBBBBB
         gettext(u'Update the event details below') 
        BBBB
         gettext(u'Fill in the details to create a new event') 
        BBBBB
    XXXX
XXXXXX

XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    
    BB BBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
        XXXXXXXXXXX
        BBBBBB
    XXXXXX
    BBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXX X X X X XXXX XXXXXXXXXXX
                            XXXXXX
                             gettext(u'Basic Information') 
                        XXXXX
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                             gettext(u'Enter the event name in different languages') XXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXXXX XXXXXX
                                XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                            XXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                            BB BBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                        BBBBB
                    XXXXXX
                XXXXXX
            XXXXXX


            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX
                                XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                        XXXXXXX XXXXXXX XXXXXXX XXXXX XX
                                    XXXXXX
                                     gettext(u'English') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX
                                XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                        XXXXXXX XXXXXXX XXXXXXX XXXXX XX
                                    XXXXXX
                                     gettext(u'French') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                    XXXXX
                XXXXXX

                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXX
                        XXXXXX XXXXXX
                            XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXX
                            XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXX
                                XXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to French') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXX
                                    XXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                        BB BBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
                    XXXXX
                        XXXXXX XXXXXX
                            XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXX
                            XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXX
                                XXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to English') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXX
                                    XXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                        BB BBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXX XXXXXXX XXXXX XXXXX X X XXXXXXXXXX X X XXXXXXXXXXXXX X X XXXXXXXXXXXXXXXX XXXXXXX X X XXXXXXXXXXXXXXX X X XXXX XXXX
                        XXXXXXX
                    XXXXXX
                     gettext(u'Description') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Event description and details') XXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX
                                XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                        XXXXXXX XXXXXXX XXXXXXX XXXXX XX
                                    XXXXXX
                                     gettext(u'English') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX
                                XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                        XXXXXXX XXXXXXX XXXXXXX XXXXX XX
                                    XXXXXX
                                     gettext(u'French') 
                                XXXXXXX
                            XXXXXXXXX
                        XXXXX
                    XXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXX
                        XXXXXX XXXXXX
                            XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX
                            XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXX
                                XXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to French') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXX
                                    XXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
                    XXXXX
                        XXXXXX XXXXXX
                            XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX
                            XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXXX XXXXXXX XXXXXX XXXXXXX X XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXX X XXXXXXXX
                                XXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Translate to English') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXX X X XXXXXXXXXXXXX X X XXXXX X XXXXXXX XXXXXXXXXXX XXXXX X XXX XXXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXXXXXX
                                    XXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXX XXXXX XXXXXX XXXXXX XXXXXXX X X XXXXXXXXX X X XXXXXXXXXX X X XXXX XXXXXX X X XXX XXXX
                        XXXXXXX
                    XXXXXX
                     gettext(u'Event Details') 
                XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Location, dates, time and pricing') 
                XXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                XXXXX
                    XXXXXX XXXXXX
                        XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                XXXXX
                    XXXXXX XXXXXX
                        XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                XXXXX
                    XXXXXX XXXXXX
                        XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                XXXXX
                    XXXXXX XXXXXX
                        XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXXX
                    XXXXXX XXXXXX
                        XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXXX
                    XXXXXX XXXXXX
                        XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXXX
                    XXXXXX XXXXXX
                        XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXXX
                    XXXXXX XXXXXX
                        XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXX
                        XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Images') XXXXX
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                     gettext(u'Upload images for this event (max 10). Images will be automatically optimized.') XXXX
            XXXXXX

            
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                        BB BBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXX XXXXXXXXXX XXXXXX
                                XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                        XXXXXX
                        BBBBB
                        XXXX XXXXXXXXXXXXXXX
                            
                            XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBB gettext(u'Replace Image') BBBB gettext(u'Upload Image') BBBBB
                            XXXXXXXX
                            
                            BB BBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                        XXXXXX
                        BB BBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                
                                XXXXX
                                    XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXX
                            XXXXXXXX
                        XXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                 gettext(u'Add Another Image') 
            XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Cancel') 
        XXXX
        XXXX XXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXX X X XXXXXX X X X XXX XXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX X X XXXXXXXX XXXXXXX XXX X X XXXXXXX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                BB BBBBBB gettext(u'Update Event') BBBB gettext(u'Save Event') BBBBB
            XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXXX

BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX

        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX

        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X

    XX XXXXXX XXXXXXX XXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXX XX XXXXXXXXX X
            XXXXXXXXXXXXXX XXXXXX XX XXXXXX XXXXXXX XXXXXXX
            XXXXXXX
        X

        XX XXXXX XXX XXXXX XXXXX XXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXX XXXX XXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXX XXX XXXX XXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXX XXXXXXXXXXXXXXX X XXX

        XX XXXXXX XXX XXXXXXXX XXXXX XXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXX XXXXXX XXXXXXXX XX XXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXX XX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXX XXXXX XXXXX XXXXX
        XXXXXXXXXXXXXXXX X XXXXXXXXX X XX
    XXX

    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXX XX XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX X
            XXXXX XXXXXXXXX X XXXXXXXXXXX
            
            XX XXXXX XXXXXXX XXXX XXX XXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXXX X
                XXX X
                    XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXX
                    
                    XX XXXXXXXXXXXXX XX XXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXX XX X
                            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXX X XXXXXXXX
                            XXXXXXXXXXXXXXXXXX X XXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX
                    X
                X XXXXX XXXXXXX X
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX
                X
            X
        XXX
    X

    XX XXXXXXXXXXX XX XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX X
            XXXXX XXXXXX X XXXXXXXXXXX
            
            XX XXXXX XXXXXXX XXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXX X
                XXX X
                    XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXX
                    
                    XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXX X
                        XX XXX XXXXXXX XXXXXXXX XXXX XXXXXXXX XXXXXXXX XX XXXXX
                        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        
                        XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXX X XXXXXXX
                            XX XXXXXX XXXXXXX XXXXXXXX XXXXX XXXXXXXX XX XXXXXXX XXXX XXXXXX
                            XXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXXXXXXXXXX XX XXXXXXXXXXXX X XXXXXXXXXXXX XX XXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX
                    X
                X XXXXX XXXXXXX X
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX
                X
            X
        XXX

        XX XXXXXXX XXXXXX XX XXXX XX XXXX XX XXXXXXX XXXXXXXX
        XX XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        X
    X

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXX
BBBBBBBB BBBBBBBBBBB