BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Events List') BBBBBBBB BBBBB

BBBBB BBBB
   XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
         XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX XX XXXX XXXXXXXX XXXXX XXXXXX XXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXX XX XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX XXX XX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XX XXX XXXXXX XXXXXXXXXXXX
          gettext(u'List') 
      XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
         XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          gettext(u'Add') 
      XXXX
   XXXXXX

    XXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Mes Événements') XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Gérez vos événements publiés') XXXX
    XXXXXX

    XXXX XXXXXXX XXXXXX XXXXX XXX
    BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X XXXXXX X X X XXX XXXXXXXXX XXXXXXX X X XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX X X XXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX X X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
             gettext(u'Compte suspendu — renouveler pour publier') 
        XXXXXX
    XXXXXX
    BBBBB

    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
        BB BBBBBB
            XXXX XXXXXXXXXXXXXXX
               XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
                     XXXX
                        XXX XXXXXXXXXXX XXXXXX gettext(u'Name') XXXXX
                        XXX XXXXXXXXXXX XXXXXX gettext(u'Clicks') XXXXX
                        XXX XXXXXXXXXXX XXXXXX gettext(u'Category') XXXXX
                        XXX XXXXXXXXXXX XXXXXX gettext(u'Status') XXXXX
                        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Actions') XXXXX
                     XXXXX
                  XXXXXXXX
                  XXXXXXX
                     BBB BBBBB BB BBBBBB
                     XXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                           XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
                              
                           XXXX
                        XXXXX
                        XXX XXXXXXXXXXX XXXXXX
                           XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                              FFFFFFFFF
                           XXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXX XXXXXX
                           FFFFFFFFFFF
                        XXXXX
                        XXX XXXXXXXXXXX XXXXXX
                           BB BBBBBBBBBBBB BB BBBBBBBBBB
                           XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                               gettext(u'Active') 
                           XXXXXXX
                           BBBB BBBBBBBBBBBB BB BBBBBBBBB
                           XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                               gettext(u'Pending') 
                           XXXXXXX
                           BBBB
                           XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                               gettext(u'Rejected') 
                           XXXXXXX
                           BBBBB
                        XXXXX
                        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXX
                           XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                              XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Edit') XXXX
                              XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Delete') XXXXXXXXX
                           XXXXXX
                        XXXXX
                     XXXXX
                     BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBB
                     BBBBBB
                  XXXXXXXX
               XXXXXXXX
            XXXXXX
        BBBB
            XXXX XXXXX XXXXX XXXXXXXXX XXXXX XX XXX
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX XXXXXX XXXXXXX X X XXXXXXXXX X X XXXXXXXXXX X X XXXX XXXXXX X X XXX XXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Aucun événement') XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXX
                     gettext(u'Créez votre premier événement pour le faire apparaître ici.') 
                XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Ajouter un événement') 
                XXXX
            XXXXXX
        BBBBB
    XXXXXX
  XXXXXX
BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXX XXX X
    XXXXX XXX X XXXX XXX XXXX
        X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX
X

XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX X
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
    XXX
X
XXXXXXXXX
BBBBBBBB BBBBBBBBBBB