BBBB BBBBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX

XXXXXX
     XXXXX XXXXXXXXXXXXXXXX
     XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
     XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBXX
     BBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
     XXXXXXXXXXXXXXXXX X BBBBB BBBBBBBBBBBBB BBBBBXXXXXXXX
     XXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          X XXXX X
               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          X
     XXXXXXXXX

XXXXXXX

XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

     BBBBB BBBBBBBBBBBB BBBB
     XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     XXXXXXX XXXXXBBBBBB BBBBBBBBBXXXXXXXXXXX
     BBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
     BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXX

XXXXXXX
