BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Login') BBBBBBBB BBBBB

BBBBB BBBB
XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBX XXXXXXXXXXX
        XXXX
        XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                     gettext(u'Sign in to your account') 
                XXXXX
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                    BBBBBBBBBB
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            FFFFFFF F
                        XXXXXX
                    BBBBB
                    BBB BBBBB BB BBBB
                        XXXXX
                            XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                
                            XXXXXXXX
                            
                            BB BBBBBBBBBBBBBBB
                                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                    
                                XXXX
                            BBBBB
                            BB BBBBBBBBBBBB
                                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    FFFFFFF F
                                XXXX
                            BBBBB
                        XXXXXX
                    BBBBBB
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                 gettext(u'Forgot password?') 
                            XXXX
                        XXXXXX
                    XXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Sign in') 
                    XXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                         gettext(u'Don’t have an account yet?')  XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sign up') XXXX
                    XXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB BBBB
