BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Password updated') BBBBBBBB BBBBB

BBBBB BBBB
XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                     gettext(u'Your password has been reset') 
                XXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                     gettext(u'You can now sign in using your new credentials.') 
                XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Sign in') 
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB BBBB
