BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Change password') BBBBBBBB BBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                 gettext(u'Change password') 
            XXXXX

            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                 gettext(u'Use a strong password that you do not reuse anywhere else.') 
            XXXX
        XXXXXX
        XXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            BBBBBBBBBB
            BB BBBBBBBBBBBBBBBBBBBBB
            XXXX
                XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                FFFFFFF F
            XXXXXX
            BBBBB
            BBB BBBBB BB BBBB
            XXXXX
                XXXXXX XXXXXX
                    XXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    
                XXXXXXXX
                
                BB BBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    FFFF
                XXXXXX
                BBBBB
                BB BBBBBBBBBBBB
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    FFFFFFF F
                XXXX
                BBBBB
            XXXXXX
            BBBBBB
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBX
                    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Cancel') 
                XXXX
                XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Save new password') 
                XXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBB