BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Choose a new password') BBBBBBBB BBBBB

BBBBB BBBB
XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXX
                BB BBBBBBBBB
                    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                         gettext(u'Set your new password') 
                    XXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                        BBBBBBBBBB
                        BB BBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                FFFFFFF F
                            XXXXXX
                        BBBBB
                        BBB BBBBB BB BBBB
                            XXXXX
                                XXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                    
                                XXXXXXXX
                                
                                BB BBBBBBBBBBBBBBB
                                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                        
                                    XXXX
                                BBBBB
                                BB BBBBBBBBBBBB
                                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                        FFFFFFF F
                                    XXXX
                                BBBBB
                            XXXXXX
                        BBBBBB
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'Update password') 
                        XXXXXXXXX
                    XXXXXXX
                BBBB
                    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                         gettext(u'Invalid or expired link') 
                    XXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                         gettext(u'Please restart the password reset process to receive a new link.') 
                    XXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'Request another link') 
                        XXXX
                    XXXXXX
                BBBBB
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB BBBB
