BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Register') BBBBBBBB BBBBB

BBBBB BBBB
XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBX XXXXXXXXXXX
        XXXX
        XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                     gettext(u'Create an account') 
                XXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                    BBBBBBBBBB
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            FFFFFFF F
                        XXXXXX
                    BBBBB
                    BBB BBBBB BB BBBB
                        XXXX XXXXXXXBB BBBBBBBBBB BB BBBBBBBBBBB BB BBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXXXXBBBBBXX
                            XXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                
                            XXXXXXXX
                            
                            BB BBBBBBBBBBBBBBB
                                XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                    FFFF
                                XXXXXX
                            BBBBB
                            BB BBBBBBBBBBBB
                                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    FFFFFFF F
                                XXXX
                            BBBBB
                        XXXXXX
                    BBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'Create account') 
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                     gettext(u'Already have an account?')  XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sign in') XXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB BBBB
