BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Settings') BBBBBBBB BBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXX


    BB BBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX
                XXXXXXX
                XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Subscription expiring soon') XXXX
                    XXX gettext(u'You have %(days)s day(s) left. Renewal date: %(renew_date)s.') SSS SSSS SSSSSSSS SSSSSS SSSSS SSSSSSS SSSSS SSSSSSSSSSSSSSSXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    BBBBB

    XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXX
                            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                            XXXXX
                            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                 gettext(u'Signed in as')  FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                            XXXX
                        XXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBB
                                
                            BBBB
                                 gettext(u'Unknown role') 
                            BBBBB
                        XXXXXXX
                    XXXXXX
                XXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                    BBBBBBBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            FFFFFFF F
                        XXXXXX
                    BBBBB
                    XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBB
                            XXXX BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBBX
                                XXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                    
                                XXXXXXXX
                                
                                BB BBBBBBBBBBBBBBB
                                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                        
                                    XXXX
                                BBBBB
                                BB BBBBBBBBBBBB
                                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                        FFFFFFF F
                                    XXXX
                                BBBBB
                            XXXXXX
                        BBBBBB
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'Save changes') 
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Security') XXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                     gettext(u'Update your password frequently to keep your workspace safe.') 
                XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Change password') 
                XXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Session') XXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                     gettext(u'Need a fresh start? You can sign out of this device safely.') 
                XXXX
                XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Logout') 
                    XXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Subscription overview') XXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                     gettext(u'Konnect integration is coming soon. These values are placeholders for now.') 
                XXXX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                 gettext(u'Open Konnect (Soon)') 
            XXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX
                        XXX XXXXXXXXXXX XXXXXX gettext(u'Plan') XXXXX
                        XXX XXXXXXXXXXX XXXXXX gettext(u'Status') XXXXX
                        XXX XXXXXXXXXXX XXXXXX gettext(u'Started') XXXXX
                        XXX XXXXXXXXXXX XXXXXX gettext(u'Renews') XXXXX
                        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Days left') XXXXX
                    XXXXX
                XXXXXXXX
                XXXXXXX
                    BB BBBBBBBBBBBBBBBBB
                        BBB BBB BB BBBBBBBBBBBBBBBBB
                            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXX XXXXXXXXXXX
                                XXX XXXXXXXXXXX XXXXXX
                                    BB BBBBBBBBBBBBBBBXXXXXXXBBBBB
                                XXXXX
                                XXX XXXXXXXXXXX XXXXXX
                                    BB BBBBBBBBBBBBBBXXXXXXXBBBBB
                                XXXXX
                                XXX XXXXXXXXXXX XXXX XXXXXXXXXXXX
                                    
                                XXXXX
                            XXXXX
                        BBBBBB
                    BBBB
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                 gettext(u'No subscription data yet. Konnect billing will appear here once connected.') 
                            XXXXX
                        XXXXX
                    BBBBB
                XXXXXXXX
            XXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBB
