BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB
    BB BBBBBB gettext(u'Edit Partner') BBBB gettext(u'Add Partner') BBBBB
BBBBBBBB BBBBB

BBBBB BBBB
XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
    XXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            BB BBBBBB gettext(u'Edit Partner') BBBB gettext(u'Add Partner') BBBBB
        XXXXX
        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Upload a 300x200 logo and provide details.') 
        XXXX
    XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Back to list') 
    XXXX
XXXXXX

XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    
    BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXBBBBBB
        XXXXXX
    BBBBB

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXX
            XXXXX
                XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                XXXXXXXX
                
                BB BBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX

            XXXXX
                XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                     gettext(u'Email Address') BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                XXXXXXXX
                
                BB BBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX

            XXXXX
                XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                XXXXXXXX
                
                BB BBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX

            XXXXX
                XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                    XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                
                BB BBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXX
                        XXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX

           XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        
    XXXXXXXX
    
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           BBB BBBBBBBB BB BBBBBBBBBBBBBB
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX
                        XXXXXXX
                        XXXXXXXX
                        XXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBB
                        XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                        
                    XXXXXXXX
                XXXXXX
            BBBBBB
        XXXXXX
    BBBB
        XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
             gettext(u"Aucune localisation disponible pour le moment. Veuillez créer des localisations d'abord.") 
        XXXXXX
    BBBBB

    BB BBBBBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            
        XXXX
    BBBBB

    BB BBBBBBBBBBBBBBBBBBBBB
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBBBB
    BBBBB
XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Cancel') 
        XXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            BB BBBBBB gettext(u'Update Partner') BBBB gettext(u'Save Partner') BBBBB
        XXXXXXXXX
    XXXXXX
XXXXXXX
BBBBBBBB BBBB