BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Partners') BBBBBBBB BBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
         gettext(u'List') 
    XXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Add') 
    XXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX
                XXX XXXXXXXXXXX XXXXXX gettext(u'Logo') XXXXX
                XXX XXXXXXXXXXX XXXXXX gettext(u'Name') XXXXX
                XXX XXXXXXXXXXX XXXXXX gettext(u'Assigned Locations') XXXXX
                XXX XXXXXXXXXXX XXXXXX gettext(u'Link') XXXXX
                XXX XXXXXXXXXXX XXXXXX gettext(u'Status') XXXXX
                XXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBBB BB BBBBBBBB
                XXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXXXX
                        BB BBBBBBBBBB
                            XXXX XXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
                        BBBB
                            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No image') XXXXXXX
                        BBBBB
                    XXXXX
                    XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        
                    XXXXX
                    
                    XXX XXXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                            BBB BBB BB BBBBBBBBBBBBBBBBBB
                                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                                    
                                XXXXXXX
                            BBBBB
                                XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX gettext(u'No locations') XXXXXXX
                            BBBBBB
                        XXXXXX
                    XXXXX

                    XXX XXXXXXXXXXX XXXXXX
                        XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
                            FFFFFFFFFFFFFFFF
                        XXXX
                    XXXXX

                    XXX XXXXXXXXXXX XXXXXX
                        BB BBBBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                 gettext(u'Verified') 
                            XXXXXXX
                        BBBB
                            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                 gettext(u'Pending') 
                            XXXXXXX
                        BBBBB
                    XXXXX

                    XXX XXXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXX XXXXXXX X X XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXX X X XXXXXXXXX X X XXX XXXXXXXXXXXXXX X X XXX XXXXX X X XXXX XXXXX X X XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXX
                                XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXX X X XXXXXXXXXXXXXXXXX XXXXX X X XXX XXXXXX X X XXX XXXXX X X XXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXX XXXXXX XXX X X XXX XXXXX X X XXXX XXXXXXXXXX X X XXXX XXXXX X X XXX XXXXX X X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    XXXXX
                XXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
            BBBBBB
        XXXXXXXX
    XXXXXXXX
XXXXXX
BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX X
   XXXXX XXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXXXX
      XXXXXXX X
          XXXXXXXXXXXX X gettext(u'Search partners...') XX
          XXXXXXX X gettext(u'No partners found') XX
          XXXXX X gettext(u'Showing {start} to {end} of {rows} partners') X
      X
   XXX
X
XXXXXXXXX
BBBBBBBB BBBBBBBBBBB