BBBB BBBBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXX XXXXXXXXXXXXXXX

XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBXX
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
        XXXXXXXXXXXXXXX X X XXXXXXXXX XXXXXXX X
    XXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
    
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XXXXXXXXX

    XXXXXXXXXXXXXXXXX XXX X BBBBB BBBBBBBBBBBBBXXXXXXXX

    XXXXXXX
        XXXX X XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX X
        XXXXXX X XXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXX XXXX XXXXX X
        XXXXXXXXXXX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXXXXX
    
    BBBBB BBBBBBBBBBBBBBBBBBB
XXXXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX

    BB BBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXXXXXXX
        BBB BBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX
            BB BBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXXXXX XXXXXXXXXX
            BBBB BBBBBBBBBBBB BB BBBBBBBXXXXXXXXXX XXXXXXXXXX
            BBBBXXXXXXXXXXX XXXXXXXXXXBBBBBXX
            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                BB BBBBBBBBBBBB BB BBBBBBBBBXBBBB BBBBBBBBBBBB BB BBBBBBBXBBBBXXBBBBB
            XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX
        BBBBBB
    XXXXXX
    BBBBB

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBB 
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB 

    XXXX XXXXXXXXXX XXXXXXXX XXXXXXX
        XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB BBBBBBBBBBBBBBB
        XXXXXX
    XXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XX XXXXXX
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX X
                XXXXXXXXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XX X XXXXXXXXXXXXXXX XX XXXXX
                XX XXXX X XXXXX X XXXXX
            XXX

            XX XXXXX XXXXXX
            XXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX X
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XX
                    XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                    X XXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    X
                XXX
            X
        XXX
    XXXXXXXXX

    BBBBB BBBBBBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX