BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBXXXXXX XX XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
  XXXXX XXXXXXXXXXXX XXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXX

      XXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXX XXX XXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXXXXXFFFFFFFFFFX
              XXXXXXXXXXXXXXXX XXXXXXXXX
              XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXX

          BB BBBBBB
          XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXX
            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
              XXXXXXXXX XX XXXXXXXXXXXXXXXXXX
              XXX 
            XXXX
          XXXXXX
          BBBBB

          BB BBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXX
            XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX
          XXXXXX
          BBBBB

          XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXX XX XXXXXX
          XXXXXXXXX
        XXXXXXX
      XXXXXX

    XXXXXX
  XXXXXXX
XXXXXX
BBBBBBBB