BBBB BBBBBB BBBB
XXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXXXXXXX XXXXX XXXXXX XXXX XXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX

        XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX
            XXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                XXXXX XXXXXXXXXX XXXXXXXXXXXXX X X X XXXXXXXXXXXX XXX XXX X X X XXXXX XXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX X X X X XX XXXXXXXXXXXXXXX X X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXX
              XXXXXX
            XXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Dashboard') XXXXXXX
          XXXX
        XXXXX

        XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX
            XXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                XXXXX XXXXXX XXX X X X XXXXXXXXXXXX X X X XXX XXXXXXXXXX X X X XXX XXXXXXXXX X X X XXX XXXXXXX X X X XXX XXXXXXXXXXX XXXX X X X X X XXXXXX X X X X XXXXXXXXXXXXXXXXXXXX X X X X X XXXXX X X X X XXXXXXX
              XXXXXX
            XXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Événements') XXXXXXX
          XXXX
        XXXXX

        XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX
            XXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXX X X X X XXXXXXXXXXXXX XXXXXXXXX X XXXXX XXXXXXXXXXXXX XXXXX X X X X XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXX XXXXXXXXXXXXXX XXXXX X X X XX XXXXXXXXXXXXXX XXXXX XXXXXX X XXXXXX XXXXXXXXXXXXX XXXXX X X X XX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX X X X X XXXXXXXXXXXXXX XXXXXXXXXX XX XXXXX XXXXXXXXXXXXXX XXXXX X X X X XXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXX XXXXXXXXXXXXXX XXXXX X X X XX XXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX X X X XX XXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXX XXXXXX
              XXXXXX
            XXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Publicités') XXXXXXX
          XXXX
        XXXXX

        XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX
            XXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                XXXXX XXXXXX XXXXX X X X XXX XXXXXX X X X X X XXXXXX X X X X XXXXXXX X X X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX XXXXXX X X X X XXXXXXX X X X X X XXXXX
              XXXXXX
            XXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Abonnement') XXXXXXX
          XXXX
        XXXXX

      XXXXX
    XXXXXX

    XXXX XXXXXXXXXX X XXXXXX XXX
    XXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Compte') 
      XXXX
      XXX XXXXXXXXXXXXXXXXXX
        XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX
            XXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX X X X XXXXXXXXXXXXX XXXXXXXXX XXX X X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX X X X XX XXXXXXXX XXX X X X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX X X XXXXXXX XXXXXXX XXXXXXXX XXX X X X X XXXXXXXXXXXXXXXX XXXXXXXXX XXX X X X XX XXXXXXX XXX X X X X XXXXXXXXXXXXXX XXXXXXXXXXXXX XXX X X X X XXXXXXXXXXX XXXXXXXXX XXX X X X XXXXX XXXXXXX XXXXXXXXXXXXXXX XXX X X X X XXXXXXXXXX XXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX X X X XXXXX XXXXXXXXXXXXXXXXX XXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX X X X XXXXXXXXXXXXX XXX X X X XX XXXXXXX XXXXX XXX X X X XXX XXX XXX X X X X XXXXX
              XXXXXX
            XXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Paramètres') XXXXXXX
          XXXX
        XXXXX
      XXXXX
    XXXXXX

  XXXXXX
XXXXXXXX